Minor: print a more general error message when cannot get resources; it is not only the insufficient number of CPUs, can be RAM, shmem, etc.

diff --git a/util/applications/comma-test-run b/util/applications/comma-test-run
--- a/util/applications/comma-test-run
+++ b/util/applications/comma-test-run
@@ -700,7 +700,7 @@ function run_single_test()
                         report_waiting "waiting for resources"
                         [[ "$max_wait_time" != "forever" ]] && {
                             if gawk '{ a=$1 > $2; exit !a }' < <( echo $wait_time $max_wait_time ) ; then
-                                echo "$name: in '$dir', could not get $parallel CPUs for ${wait_time}s, failed to run" >&2
+                                echo "$name: in '$dir', could not get requested resources for ${wait_time}s, failed to run" >&2
                                 result=1
                                 break
                             fi
