Do not report errors for tests that fail due to (known) lack of shared memory, just re-start them.

diff --git a/util/applications/comma-test-run b/util/applications/comma-test-run
--- a/util/applications/comma-test-run
+++ b/util/applications/comma-test-run
@@ -502,28 +502,27 @@ function run_single_test()
                 }
                 [[ "$first" == "false" && "$options_debug" != "0" ]] && echo " end of wait" >&2
                 first="true"
-                local passed="false"
-                if [ -f ./input ] ; then cat ./input ; fi \
-                    | comma_progress_named "$our_stats_progress" "$dir" "$test_exec" "$path" "$verbose" 2>&1 \
-                    | if [[ -f ./expected ]]; then comma-test-match ./expected 2>&1 | fail_on_output; else cat > /dev/null; fi
-                if status_ok ; then passed="true" ; fi
+                local output error_files
+                find . -name out_of_shared_memory | xargs rm -f
+                output=$( if [ -f ./input ] ; then cat ./input ; fi \
+                    | comma_progress_named "$our_stats_progress" "$dir" "$test_exec" "$path" "$verbose" \
+                    | if [[ -f ./expected ]]; then comma-test-match ./expected 2>&1 | fail_on_output; else cat > /dev/null; fi )
+                local test_failed=$?
                 release_resources "$dir" "$verbose_resources"
-                [[ "$passed" == "true" ]] && {
-                    message_ "$name: test $counter: $dir: succeeded"
-                    break
-                } || {
-                    local error_files
-                    error_files="$( find . -name out_of_shared_memory )"
-                    [[ -n "$error_files" ]] && {
-                        [[ "$first" == "true" ]] && { echo "$name_offset ran out of shared memory, will try again ..." >&2; first="false"; }
-                        echo "$error_files" | xargs rm -f
-                        continue
-                    } || {
-                        result=1
-                        error_ "$name: $dir: failed"
-                        break
-                    }
+                error_files="$( find . -name out_of_shared_memory )"
+                [[ -n "$error_files" ]] && {
+                    [[ "$first" == "true" ]] && { echo "$name_offset ran out of shared memory, will try again ..." >&2; first="false"; }
+                    echo "$error_files" | xargs rm -f
+                    continue
                 }
+                [[ -n "$output" ]] && echo "$output" >&2
+                [[ "$test_failed" == "0" ]] && {
+                    message_ "$name: test $counter: $dir: succeeded"
+                } || {
+                    result=1
+                    error_ "$name: $dir: failed"
+                }
+                break
             done
             cd $basedir
         fi
