allow test configs to be inherited

diff --git a/util/applications/comma-test-run b/util/applications/comma-test-run
--- a/util/applications/comma-test-run
+++ b/util/applications/comma-test-run
@@ -123,7 +123,6 @@ function description_others()
 --debug; much more debug output
 --document,--doc; do not run tests, only output to stdout a collated test documentation in informal way, if --junit present, produce junit-like output (todo)
 --junit=[<file>]; output to file junit record compatible with jenkins for each test
---interactive; allow test scripts to access an X window to provide supervised/interactive tests, if present tests cannot be run in parallel
 --no-ansiterm-control-characters,--no-control-characters,--raw; unstyled output (no ANSIterm control characters)
 --output-directories,--dry-run,--dry; output list of test directories intended to run and exit
 --path=[<dir>]; data-storage directory for tests, default: none, let the tests define it
@@ -409,13 +408,13 @@ function exclude_generic_tests()
 
 # find "test" file inside a path, checking in each subdirectory (starting from the full path)
 # arguments: <path> <file to find>
-function closest_test_in_path()
+function closest_file_in_path()
 {
-    local path=$1
-    local file="test"
-
+    local path="$1"
+    local file="$2"
+    
     # sanity check (and avoid infinite loop)
-    if [[ -z "$path" ]]; then echo "$name: error: empty path in closest_file_in_path()" >&2; exit 1; fi
+    if [[ -z "$path" || -z "$file" ]]; then echo "$name: error: empty path in closest_file_in_path()" >&2; exit 1; fi
     # get canonical name (so path always starts with "/")
     path=$( readlink -e "$path" )
 
@@ -423,14 +422,14 @@ function closest_test_in_path()
         if [[ -d "$path/$file" ]]; then
             echo "$name: warning: \"$path/$file\" is a directory (expected an executable script); ignoring" >&2
         elif [[ -f "$path/$file" ]]; then
-            if [[ -x "$path/$file" ]]; then echo $path/$file; break
-            else echo "$name: warning: \"$path/$file\" is not executable; ignoring" >&2; fi
+            if [[ $file == "test" && ! -x "$path/$file" ]]; then echo "$name: warning: \"$path/$file\" is not executable; ignoring" >&2 
+            else echo $path/$file; break; fi
         elif [[ $path == "/" ]]; then break
         fi
         path=$( dirname "$path" )
     done
 }
-export -f closest_test_in_path
+export -f closest_file_in_path
 
 # "dirname" with multiple arguments allowed (since some versions of "dirname" don't allow them)
 function get_dirnames()
@@ -537,7 +536,11 @@ export -f default_requirements
 
 function get_required_resources()
 {
-    ( default_requirements; [[ -f ./config ]] && cat ./config; ) | comma_path_value_take_last | name-value-convert --from path-value --to json
+    ( 
+        default_requirements
+        local config=$(closest_file_in_path "." "config")
+        [[ -f "$config" ]] && cat "$config"
+    ) | comma_path_value_take_last | name-value-convert --from path-value --to json
 }
 export -f get_required_resources
 
@@ -612,8 +615,7 @@ function run_and_match_test()
 {
     local test_failed error_files
 
-    local env_variables="PYTHONPATH"
-    (( options_interactive )) && env_variables+=",XDG_RUNTIME_DIR,DISPLAY"
+    local env_variables="PYTHONPATH,XDG_RUNTIME_DIR,DISPLAY"
     
     rm -rf output || { error_and_junit_ "Unable to remove 'output' directory" ; return 1 ; }
     mkdir -p output || { error_and_junit_ "Unable to make 'output' directory" ; return 1 ; }
@@ -681,8 +683,9 @@ export -f run_and_match_test
 function get_test_timeout()
 {
     local config_timeout
-    if [[ -f ./config ]]; then
-        config_timeout=$( cat ./config | name-value-get --from=path-value "run/max_time" )
+    local config=$(closest_file_in_path "." "config")
+    if [[ -f "$config" ]]; then
+        config_timeout=$( cat "$config" | name-value-get --from=path-value "run/max_time" )
         if [[ -n $config_timeout ]]; then
             if [[ ! $config_timeout =~ ^[0-9]+$ || $config_timeout -eq 0 ]]; then
                 echo "$name: warning: illegal run/max_time '$config_timeout' in $( pwd )/config (expected integer > 0); using default $max_run_time" >&2
@@ -820,7 +823,7 @@ function run_single_test()
     elif disabled_ "optional" "$dir" "$options_run_optional" ; then
         warning_ "$name: test $counter: $dir: optional, skipped"
     else
-        test_exec=$( closest_test_in_path "$dir" )
+        test_exec=$( closest_file_in_path "$dir" "test" )
         if [[ -z "$test_exec" ]]; then
             error_ "$name: error: no \"test\" script found in any parent directory of $dir"
             result=1
@@ -1044,7 +1047,6 @@ have_max_parallel=$(( have_max_parallel_equal > 0 || have_max_parallel_space > 0
 (( $options_parallel == 0 && $have_max_parallel == 0 )) && options_max_parallel=1
 (( $have_max_parallel != 0 )) && options_parallel=1
 (( $options_max_parallel < 1 )) && { error_ "$name: number of parallel tests $options_max_parallel < 1"; exit 1; }
-(( $options_max_parallel > 1 && options_interactive == 1 )) && { error_ "$name: cannot run interactive tests in parallel"; exit 1; }
 (( $options_max_memory_main < 1 )) && { error_ "$name: amount of shared memory $options_max_memory_main < 1 MB"; exit 1; }
 (( $options_max_memory_shared < 1 )) && { error_ "$name: amount of shared memory $options_max_memory_shared < 1 MB"; exit 1; }
 [[ "$options_max_wait_time" != "forever" ]] && {
