FP-1802: provide explicit option to recommend the tests to be reviewed instead of parsing stderr for the same information. Also, sort out '--verbose' output a bit; still messy.

diff --git a/util/applications/comma-test-resources b/util/applications/comma-test-resources
--- a/util/applications/comma-test-resources
+++ b/util/applications/comma-test-resources
@@ -68,6 +68,7 @@ function description()
 --threshold-cpus=[<num>]; ignore CPU usage (count) below the threshold, bytes; default: $default_threshold_cpus
 --threshold-mismatch=[<value>]; flag for review if relative mismatch of current and recommended values exceeds limit; default: $default_threshold_mismatch
 --performance-log=[<name>]; look for performance logs named <name>; default: '$default_performance_log'
+--report-tests-to-review; in 'analyse' mode, output the list of tests recommended for review
 --human-readable; output memory values in kB or MB instead of bytes
 EOF
 }
@@ -132,9 +133,7 @@ Examples (more advanced):
     more detailed information about them (in a second call):
 
         comma-test-run --dry-run \\
-            | comma-test-resources analyse --threshold-mismatch=0.7 2>&1 \\
-            | grep 'review shared memory usage' \\
-            | sed 's@.* usage in @@;'"s@'@@g" \\
+            | comma-test-resources analyse --threshold-mismatch=0.7 --report-tests-to-review \\
             | comma-test-resources analyse --verbose --human-readable --threshold-mismatch=0.7
 
 EOF
@@ -182,11 +181,11 @@ function recommend()
     (( options_verbose > 0 )) && echo "$scriptname: recommend for '$test_dir'" >&2
     local performance_log="$test_dir/$options_performance_log"
     [[ ! -f "$performance_log" ]] && {
-        echo "$scriptname: log file '$performance_log' not found" >&2
-        return 1
+        (( options_verbose > 0 )) && echo "$scriptname: log file '$performance_log' not found" >&2
+        return 3
     }
     [[ ! -s "$performance_log" ]] && {
-        echo "$scriptname: log file '$performance_log' empty" >&2
+        (( options_verbose > 0 )) && echo "$scriptname: log file '$performance_log' empty" >&2
         echo "$test_dir/recommended/resources/cpus=0"
         return 0
     }
@@ -263,17 +262,25 @@ function analyse()
     (( options_verbose > 0 )) && echo "$scriptname: analyse '$test_dir'" >&2
 
     local recommended
-    recommended=$( recommend "$test_dir" | grep -v ^# )
-    (( $? == 0 )) || { echo "$scriptname: automatic resources recommendation failed" >&2; return 1; }
+    recommended=$( recommend "$test_dir" | sed '/^#/d' )
+    (( $? != 1 )) || { echo "$scriptname: automatic resources recommendation failed" >&2; return 1; }
 
     local config="$test_dir/config"
     # possible special case
     if [[ ! -s "$config" ]] ; then
         if [[ -n "$recommended" ]] ; then
-            echo "$scriptname: attention, add resources management in '$test_dir'" >&2
-            echo "$recommended"
+            if (( options_report_tests_to_review )) ; then
+                echo "$test_dir"
+            else
+                echo "$scriptname: add resources management in '$test_dir'" >&2
+                echo "$recommended" >&2
+            fi
         else
-            echo "$scriptname: no resources management needed in '$test_dir'" >&2
+            if (( options_report_tests_to_review )) ; then
+                echo "$test_dir"
+            else
+                echo "$scriptname: no resources management needed in '$test_dir'" >&2
+            fi
         fi
         return 0
     fi
@@ -288,39 +295,45 @@ function analyse()
     comma_path_value_to_var --prefix="current" < <( cat "$config" | comma_storage_to_bytes )
 
     # special case
-    [[ "$current_resources_serial" == "true" ]] && {
-        (( options_verbose > 0 )) && echo "test already marked as serial" >&2
+    if [[ "$current_resources_serial" == "true" ]] ; then
+        (( options_verbose > 0 )) && echo "$scriptname: test already marked as serial" >&2
         recommended_resources_serial="true"
-    } || {
+    else
         # not serial (human-marked) and lightweight
         [[ -n "$recommended" ]] || {
-            echo "$scriptname: attention, may remove resources management in '$test_dir'" >&2
+            if (( options_report_tests_to_review )) ; then
+                echo "$test_dir"
+            else
+                echo "$scriptname: may remove resources management in '$test_dir'" >&2
+            fi
             return 0
         }
-    }
+    fi
 
     # compare recommendations with current settings; suggest review if diverge too much
-    local review=0
     comma_path_value_to_var --prefix="recommended" < <( zero_resources )
     comma_path_value_to_var < <( echo "$recommended" | sed "s@$test_dir/@@" | comma_storage_to_bytes )  # already has the 'recommended' prefix
+    local message=""
     if mismatch_exceed_threshold $current_resources_memory_shared $recommended_resources_memory_shared $options_threshold_mismatch ; then
-        review=1
-        echo "$scriptname: attention, review shared memory usage in '$test_dir'" >&2
+        message+="$scriptname: review shared memory usage in '$test_dir'\n"
     fi
     if mismatch_exceed_threshold $current_resources_memory_main $recommended_resources_memory_main $options_threshold_mismatch ; then
-        review=1
-        echo "$scriptname: attention, review main memory usage in '$test_dir'" >&2
+        message+="$scriptname: review main memory usage in '$test_dir'\n"
     fi
     if mismatch_exceed_threshold $current_resources_cpus $recommended_resources_cpus $options_threshold_mismatch ; then
-        review=1
-        echo "$scriptname: attention, review cpus usage in '$test_dir'" >&2
+        message+="$scriptname: review cpus usage in '$test_dir'\n"
     fi
-    (( review == 1 )) && {
-        echo "$recommended"
-        cat "$config" | $storage_converter | sed "s@^@$test_dir/current/@"
-    } || {
-        echo "$scriptname: current settings are fine" >&2
-    }
+    if [[ -n "$message" ]] ; then
+        if (( options_report_tests_to_review )) ; then
+            echo "$test_dir"
+        else
+            echo -e -n "$message" >&2
+            echo "$recommended" >&2
+            cat "$config" | $storage_converter | sed "s@^@$test_dir/current/@" >&2
+        fi
+    else
+        (( options_verbose > 0 )) && echo "$scriptname: current settings are fine" >&2
+    fi
 }
 
 # Handle command line
@@ -330,6 +343,8 @@ comma_path_value_to_var --prefix="options" < <( description | comma-options-to-n
 
 action="$1"
 [[ "$action" == "recommend" || "$action" == "analyse" ]] || { echo "$scriptname: unknown action '$action'" >&2; exit 1; }
+[[ "$action" != "analyse" && $options_report_tests_to_review -gt 0 ]] && { echo "$scriptname: option '--report-tests-to-review' incompatible with '$action' action" >&2; exit 1; }
+[[ $options_verbose -gt 0 && $options_report_tests_to_review -gt 0 ]] && { echo "$scriptname: do not use '--verbose' with '--report-tests-to-review'; it clutters output" >&2; exit 1; }
 
 storage_converter="cat"
 (( options_human_readable > 0 )) && storage_converter="comma_storage_to_human_readable" || storage_converter="comma_storage_to_bytes"
@@ -340,7 +355,7 @@ function act()
     local test_dir exit_status
     exit_status=0
     while read test_dir ; do
-        echo "$scriptname: process '$test_dir'" >&2
+        (( options_verbose > 0 )) && echo "$scriptname: process '$test_dir'" >&2
         [[ -d "$test_dir" ]] || { echo "$scriptname: input must be a test directory, not '$test_dir'" >&2; exit 1; }
         [[ -f "$test_dir/disabled" ]] && { echo "$scriptname: test '$test_dir' disabled" >&2; exit 0; }
         $action "$test_dir"
@@ -350,4 +365,4 @@ function act()
 }
 
 # main: either read stdin or process current directory
-[[ ! -t 0 ]] && { act; } || { echo "." | act; }
+if [[ ! -t 0 ]] ; then act; else echo "." | act; fi
