comma-test-util: add exit_on_fail_flag to stop test procedure on critical test failure

diff --git a/util/applications/comma-test-util b/util/applications/comma-test-util
--- a/util/applications/comma-test-util
+++ b/util/applications/comma-test-util
@@ -181,7 +181,8 @@ function comma_test_interactive_commands()
                 if [[ "$key" == "command" ]]; then command="$value"
                 elif [[ "$key" == "instruction" ]]; then instruction="$value"
                 elif [[ "$key" == "expected" ]]; then expected="$value"
-                else echo "$0: test '$name': expected 'command', 'instruction', or 'expected', got: '$key'" >&2; return 1; fi
+                elif [[ "$key" == "exit_on_fail" ]]; then exit_on_fail=1
+                else echo "$0: test '$name': expected 'command', 'instruction', 'expected', or 'exit_on_fail', got: '$key'" >&2; return 1; fi
             done
             [[ -n "$command" ]] || { echo "$0: $name/command not specified" >&2 ; echo "$name/status=1"; return 1 ; }
             if [[ -n "$instruction" || -n "$expected" ]]; then                
@@ -202,11 +203,12 @@ function comma_test_interactive_commands()
         local number_of_testcases=$( wc -l <<< "$test_cases" )
         local testcase_number=0 test_case_name
         while read test_case_name; do
+            exit_on_fail=0
             local escaped="${test_case_name//[/\\[}"
             local test_case=$( grep "^$escaped/" <<< "$lines" | sed "s#^$escaped/##" ) # grep --fixed-strings does not seem to work
             comma_test_interactive_test_case $test_case_name $testcase_number $number_of_testcases <<< "$test_case"
             local r=$?
-            if (( r != 0 && until_first_error )); then return $r; fi
+            if (( r != 0 && (until_first_error || exit_on_fail) )); then return $r; fi
             (( ++testcase_number ))
         done <<< "$test_cases"
     )
