comma-test-run, util/test/test_run/max_run_time: allow max run time to be specified in the config (not just with option --max-run-time)

diff --git a/util/applications/comma-test-run b/util/applications/comma-test-run
--- a/util/applications/comma-test-run
+++ b/util/applications/comma-test-run
@@ -212,6 +212,10 @@ ${brown}Load-balancing and serializing tests${none}
     No test shall take longer than the period specified by '--max-run-time'. If a test does not complete
     within this time, it is forcefully terminated and marked as failed.
 
+    The config file can override the maximum run time with the parameter max_run_time; for example:
+
+        max_run_time=600
+
 ${brown}White(and black)-listing tests${none}
     The test names in the white/black list file shall match ${brown}exactly${none} the corresponding
     names in '--dry-run' output, e.g.
@@ -561,19 +565,35 @@ function run_and_match_test()
 }
 export -f run_and_match_test
 
+function get_test_timeout()
+{
+    local timeout=$max_run_time
+    if [[ -f ./config ]]; then
+        timeout=$( cat ./config | name-value-get --from=path-value "max_run_time" )
+        if [[ ! $timeout =~ ^[0-9]+$ || $timeout -eq 0 ]]; then
+            echo "$name: error: illegal max_run_time '$timeout' in $( pwd )/config (expected integer > 0); using default $max_run_time" >&2
+            timeout=$max_run_time
+        fi
+    fi
+    echo $timeout
+}
+export -f get_test_timeout
+
 # this function runs a provided test application under the timeout command
 function run_test_with_timeout()
 {
     setup_signal_handler terminate_run_and_match_test
     export -f comma_progress_named
     export our_stats_progress dir test_exec path verbose
+    local timeout_time
+    timeout_time=$( get_test_timeout )
     if [[ "$options_estimate_resources" == "1" ]] ; then
         local our_performance_log="$comma_test_run_unique_dir/performance_log.$( mktemp --dry-run XXXXXX )"
-        timeout -k 10 -s TERM $max_run_time bash -c comma_top_wrapper\ "$our_performance_log" & comma_top_pgid=$!
+        timeout -k 10 -s TERM $timeout_time bash -c comma_top_wrapper\ "$our_performance_log" & comma_top_pgid=$!
     fi
     # Note: timeout option '-k' is missing in RHEL6, remove '-k 10' if need be
     local rv
-    timeout -k 10 -s TERM $max_run_time bash -c run_and_match_test & comma_test_run_and_match_test_pgid=$!
+    timeout -k 10 -s TERM $timeout_time bash -c run_and_match_test & comma_test_run_and_match_test_pgid=$!
     wait $comma_test_run_and_match_test_pgid
     rv=$?
     unset comma_test_run_and_match_test_pgid
