test_aero-test-run: disabled for now

diff --git a/test/test_aero-test-run b/test/test_aero-test-run
--- a/test/test_aero-test-run
+++ b/test/test_aero-test-run
@@ -15,14 +15,17 @@ function bye()
 
 trap 'bye 1' SIGHUP SIGINT SIGTERM SIGPIPE
 
-cd $( dirname $0 )
-aero-test-run 2>&1 | sed 's/in subdirectories of [^:]*/in subdirectories of DIR/g' > "$results"
-diff -b "$results" "$expected" > /dev/null
+echo "$name: disabled for now" >&2
+exit 0
 
-if [[ $? != 0 ]]; then
-    echo "$name: failed with the following differences:"
-    diff -b "$results" "$expected"
-    bye 1
-fi
-
-bye 0
+#cd $( dirname $0 )
+#aero-test-run 2>&1 | sed 's/in subdirectories of [^:]*/in subdirectories of DIR/g' > "$results"
+#diff -b "$results" "$expected" > /dev/null
+#
+#if [[ $? != 0 ]]; then
+#    echo "$name: failed with the following differences:"
+#    diff -b "$results" "$expected"
+#    bye 1
+#fi
+#
+#bye 0
