system/apt: disabled building a separate python package; in progress...

diff --git a/system/apt/comma-apt-cpack b/system/apt/comma-apt-cpack
--- a/system/apt/comma-apt-cpack
+++ b/system/apt/comma-apt-cpack
@@ -17,8 +17,8 @@ ansible-playbook "$comma_dir/system/ansible/install.python3.yml" || die "failed"
     cmake . -DCPACK_GENERATOR=DEB -DCPACK_PACKAGE_VERSION_MAJOR=$version_major -DCPACK_PACKAGE_VERSION_MINOR=$version_minor -DCPACK_PACKAGE_VERSION_PATCH=$version_patch  || die "failed"
     echo "$0: running cpack in $( pwd )" >&2
     cpack || die "failed"
-    cd ~/src/comma/python
-    echo "$0: setting up python in $( pwd )" >&2
-    python3 setup.py --command-packages=stdeb.command bdist_deb  || die "failed"
+    #cd ~/src/comma/python
+    #echo "$0: setting up python in $( pwd )" >&2
+    #python3 setup.py --command-packages=stdeb.command bdist_deb || die "failed"
     echo "$0: done" >&2
 )
