system/apt: in progress...

diff --git a/system/apt/comma-apt-cpack b/system/apt/comma-apt-cpack
--- a/system/apt/comma-apt-cpack
+++ b/system/apt/comma-apt-cpack
@@ -1,20 +1,24 @@
 #!/bin/bash
 
+function die() { echo "$0: $@" >&2; exit 1; }
+
 version_major=$1
 version_minor=$2
 version_patch=$3
 comma_dir="$4"
 [[ -n "$comma_dir" ]] || comma_dir=$( realpath ~/src/comma )
 [[ -n "$version_patch" ]] || { echo "usage: $0 <comma version major> <comma version minor> <comma version patch> [<comma dir>]" >&2; exit 1; }
-echo "$0: running ansible-playbook '$comma_dir/system/ansible/install.python3.yml'..." >&2
-ansible-playbook "$comma_dir/system/ansible/install.python3.yml"
+cd ~
+echo "$0: running ansible-playbook '$comma_dir/system/ansible/install.python3.yml' in $( pwd )..." >&2
+ansible-playbook "$comma_dir/system/ansible/install.python3.yml" || die "failed"
 (
-    cd ~/src/comma/build
+    cd ~/build/comma
     echo "$0: running cmake in $( pwd )" >&2
-    cmake -DCPACK_GENERATOR=DEB -DCPACK_PACKAGE_VERSION_MAJOR=$version_major -DCPACK_PACKAGE_VERSION_MINOR=$version_minor -DCPACK_PACKAGE_VERSION_PATCH=$version_patch
+    cmake . -DCPACK_GENERATOR=DEB -DCPACK_PACKAGE_VERSION_MAJOR=$version_major -DCPACK_PACKAGE_VERSION_MINOR=$version_minor -DCPACK_PACKAGE_VERSION_PATCH=$version_patch  || die "failed"
     echo "$0: running cpack in $( pwd )" >&2
-    cmake cpack
+    cmake cpack || die "failed"
     cd ~/src/comma/python
     echo "$0: setting up python in $( pwd )" >&2
-    python3 setup.py --command-packages=stdeb.command bdist_deb
+    python3 setup.py --command-packages=stdeb.command bdist_deb  || die "failed"
+    echo "$0: done" >&2
 )
