Provide a common status_ok definition that ignores exits on SIGPIPE. Now have to wire up to all the users.

diff --git a/application/comma-application-util b/application/comma-application-util
--- a/application/comma-application-util
+++ b/application/comma-application-util
@@ -338,3 +338,29 @@ function comma_options_has()
     echo 0
 }
 export -f comma_options_has
+
+# verify the overall exit status of a pipeline ($? reports only the status of the last step
+# in a pipeline); ignore termination by SIGPIPE
+#
+# rationale for ignoring SIGPIPE: if in a pipeline " A | B " the process "B" may exit before A,
+# so that A (pipe writer) has no reader, then A is killed by SIGPIPE and has non-zero exit status
+# however, this may be (and likely is) not an error overall, as B has simply finished
+# processing and terminated
+#
+# example
+# A | B | C | D
+# if ! status_ok ; then echo "failed"; else echo "ok"; fi
+
+# define this value once to avoid calling subprocesses inside status_ok
+SIGPIPE_STATUS=$( expr 128 \+ $( kill -l SIGPIPE ) )
+export SIGPIPE_STATUS
+
+function status_ok()
+{
+    local outcome
+    for outcome in "${PIPESTATUS[@]}" ; do
+        (( outcome == 0 || outcome == SIGPIPE_STATUS )) && return 0
+    done
+    return 1
+}
+export -f status_ok
