aero-test-match, fixm-to-python: made aero-test-match output lines like "a/b/c/expected" and "a/b/c/actual"; use Python to evaluate expressions

diff --git a/aero-test-match b/aero-test-match
--- a/aero-test-match
+++ b/aero-test-match
@@ -1,49 +1,66 @@
 #!/bin/bash
 
+name=$( basename $0 )
+
 . /usr/local/bin/aero-test-util
+
+function simple_usage()
+{
+    echo "Usage: $name [-h|--help] [-i|--input=<file>] <expected-values-file>" >&2
+    if [[ $# != 0 ]]; then exit $1; fi
+}
 
 function usage()
 {
-    echo >&2
-    echo "match input with expected values" >&2
-    echo >&2
-    echo "usage: cat some-test-output | aero-test-match <expected> [<options>]" >&2
-    echo >&2
-    echo "<expected>: file with expected outputs" >&2
-    echo >&2
-    exit 1
+    simple_usage
+    cat >&2 <<EOF
+
+Verify input against expected values.
+
+By default, input is read from stdin. Input consists of lines in the form "path=value".
+Paths may contain array indexes, e.g. abc/def[10]/xyz.
+
+The <expected-values-file> contains one boolean expression per line, referring to the path values.
+
+Examples:
+
+some_value = 5.23
+flight/weight = 28000+/-150
+abc/def[10]/xyz != "YSSY"
+(flight/weight > 3 and last/time matches "2013.*")
+
+EOF
+    if [[ $# != 0 ]]; then exit $1; fi
 }
 
-for arg in $@ ; do
-    if [[ "$arg" == "--help" || "$arg" == "-h" ]] ; then usage ; fi
+if [[ $# == 0 ]]; then simple_usage 1; fi
+
+input=
+expr_file=
+
+while [[ $# -gt 0 ]]; do
+    arg="${1#*=}"
+    case "$1" in
+        -h|--help)          usage 0;;
+
+        -i=*|--input=*)     input=$arg;;
+
+        -*)                 echo "$name: unrecognized option '$1'" >&2; exit 1;;
+
+        *)                  if [[ -z "$expr_file" ]]; then expr_file=$arg
+                            else echo "$name: unexpected argument '$1'" >&2; exit 1; fi;;
+    esac
+    shift
 done
 
-function read_path_value()
-{
-    map_name=$1
-    while IFS='=' read path value ; do
-    if [[ ! "$path" =~ ^[\ \t]*# ]] ; then
-        path=$( echo $path | sed 's/^[ \t]*//g' )
-        if [[ "$path" != "" ]] ; then eval ${map_name}["$path"]="$value" ; fi
-    fi
-    done < <( cat $2 )
-}
+if [[ -z "$expr_file" ]]; then echo "$name: missing required argument <expected-values-file>" >&2; exit 1; fi
 
-declare -A expected
-read_path_value expected $1
-declare -A actual
-read_path_value actual
+tmp_vars="vars.$$"
+cat $input | fixm-to-python --assign > "$tmp_vars"
 
-result=0
-for e in ${!expected[@]} ; do
-    if [[ ! "${actual[$e]}" =~ expected["$e"] ]] ; then
-        result=1
-        echo -e "${red}aero-test-match: on $e:${none}" >&2
-        echo -e "${red}    expected: ${expected[$e]}${none}" >&2
-        if [[ "${actual[$e]}" == "" ]] ; then echo -e "${red}         got: nothing${none}" >&2
-        else echo -e "${red}         got: ${actual[$e]}${none}" >&2 ; fi
-    fi
+# read one line at a time, since python exits for some kinds of errors
+
+cat "$expr_file" | while read line; do
+    ( cat "$tmp_vars"; echo $line | fixm-to-python --test ) | python
 done
-
-exit $result
 
