aero-test-run: allow 'expected' file to be missing (if so, or if empty, don't call aero-test-match); search for directories containing "expected" (as well as "input" or "test"); updated help text

diff --git a/aero-test-run b/aero-test-run
--- a/aero-test-run
+++ b/aero-test-run
@@ -4,21 +4,31 @@
 
 function usage_()
 {
+    echo -e "Usage: aero-test-run [<options>]" >&2
     echo >&2
-    echo -e "run all the scripts in subdirectories called 'tests' of the current directory" >&2
-    echo -e "return 0, if all tests succeed; non-zero, if failure" >&2
+    echo -e "Search for and execute tests using two different methods (the second method is preferred):" >&2
     echo >&2
-    echo -e "usage: aero-test-run [<options>]" >&2
+    echo -e "(1) run all scripts in any subdirectories called 'tests'. A non-zero exit status indicates failure." >&2
     echo >&2
-    echo -e "note: in quiet mode, only the messages containing the word \"failed\" will be displayed" >&2
+    echo -e "(2) find subdirectories containing the files 'test', 'input' or 'expected'. Execute 'test', then either:" >&2
+    echo -e "    (a) if 'expected' exists and is non-empty, compare its contents to the output of 'test' (\"path=value\" format)" >&2
+    echo -e "    (b) otherwise the success of the test depends on the exit status of 'test'." >&2
     echo >&2
-    echo -e "options" >&2
+    echo -e "If there is an 'input' or 'expected' file but no 'test' in the same directory, the 'test' script in the" >&2
+    echo -e "closest parent directory is used. If there is a 'test' by itself with no 'input' or 'expected' file," >&2
+    echo "it is only executed if there is no subdirectory containing 'input', 'expected' or 'test'." >&2
+    echo >&2
+    echo -e "Returns 0 if all tests succeed, or non-zero if any of the tests fail." >&2
+    echo >&2
+    echo -e "Note: in quiet mode, only the messages containing the word \"failed\" will be displayed" >&2
+    echo >&2
+    echo -e "Options" >&2
     echo -e "    --debug: much more debug output" >&2
     echo -e "    --quiet,-q: output only failures" >&2
     echo -e "    --path=<qstorage path>: q-storage directory; default: /mnt/q-storage" >&2
     echo -e "    --until-first-failure,-f: exit after the first failure" >&2
     echo >&2
-    echo -e "disabling tests" >&2
+    echo -e "Disabling tests" >&2
     echo -e "    to disable tests in a directory and all its subdirectories" >&2
     echo -e "    drop an empty file named ${brown}disabled${none} in that directory" >&2
     echo >&2
@@ -80,7 +90,7 @@ function escape_special_chars()
     echo $* | sed 's/[].*|&^$[]/\\&/g'
 }
 
-# arguments: a list of directories containing "test" and "input" files
+# arguments: a list of directories containing "test", "input" and "expected" files
 # Outputs the same list, excluding any directories that
 # (1) contain only "test" (no "expected" or "input" file), and
 # (2) have at least one subdirectory containing another test
@@ -201,10 +211,10 @@ if (( $dir_count > 0 )) ; then
     if [[ "$result" == 0 ]] ; then message_ "$name: tests in $dir_count subdirectories of $basedir: succeeded" ; else error_ "$name: tests in $dir_count directories: some tests failed" ; fi
 fi
 
-# search for directories containing either "test" or "input";
+# search for directories containing either "test", "input" or "expected";
 # if "test" is absent, use the "test" in the closest parent directory
 
-test_script_dirs=$( exclude_generic_tests $( get_dirnames $( find . -name "test" -or -name "input" ) 2> /dev/null | sort -u ) )
+test_script_dirs=$( exclude_generic_tests $( get_dirnames $( find . -name "test" -or -name "input" -or -name "expected" ) 2> /dev/null | sort -u ) )
 test_scripts_count=$( echo $test_script_dirs | wc -w )
 count=0
 failed_count=0
@@ -219,15 +229,13 @@ if (( $test_scripts_count > 0 )) ; then
         if [[ -z "$test_exec" ]]; then echo "$name: error: no \"test\" file found in any parent directory of $dir" >&2 ; continue ; fi
         if [[ ! -x "$test_exec" ]]; then echo "$name: error: test is not executable: $test_exec" >&2 ; continue ; fi
         message_ "$name: test $count of $test_scripts_count: $dir: running..."
-        if [[ ! -f $dir/expected ]]; then echo "$name: missing \"expected\" file in $dir: skipping" >&2; continue; fi
         basedir=$( pwd )
         cd $dir
         timestamp_file="$( mktemp -t aero-test-run-timestamp-$( basename $dir ).XXXXXX )" # capture starting time
         touch "$timestamp_file"
         if [ -f ./input ] ; then cat ./input ; fi \
             | aero_progress_named $stats_progress_csv "$dir" "$test_exec" $path $verbose 2> >( $grep_failed_ >&2 ) \
-            | aero-test-match ./expected 2>&1 \
-            | fail_on_output
+            | if [[ -s ./expected ]]; then aero-test-match ./expected 2>&1 | fail_on_output; fi
         if status_ok ; then message_ "$name: test $count of $test_scripts_count: $dir: succeeded" ; else result=1 ; (( ++failed_count )) ; error_ "$name: $dir: failed" ; fi
         report_leaked_shared "$timestamp_file" "$dir" # see if there are files in /dev/shm created past start_time and report
         cd $basedir
