aero-test-submit: added job submission and wait for completion (doesn't compare to expected results yet)

diff --git a/aero-test-submit b/aero-test-submit
--- a/aero-test-submit
+++ b/aero-test-submit
@@ -1,14 +1,20 @@
 #!/bin/bash
 
-# Note: this version is incomplete:
-# it doesn't actually add any jobs to the queue, it just prints the appropriate SQL "insert" statements.
-
 name=$( basename $0 )
 
-output_base_dir="/mnt/qstorage/log/gui/aero-test"
+submit_time=$( date --utc "+%Y%m%dT%H%M%S" )
+output_base_dir="/var/qantas/data/log/gui/aero-test"
 user_name="acceptance"
-version_to_use="prod"   # "prod", "test" or "bleeding"
+# TODO: change to "prod" when ready for release
+build_to_use="bleeding"   # "prod", "test" or "bleeding"
 task_priority=3
+db_host="129.78.214.114"
+db_port="3306"
+db_user="jobq_submit"
+db_pwd="bReWAca4rUJu"
+db_name="qdata"
+sql_command="mysql -h $db_host -P $db_port -u $db_user -p$db_pwd $db_name -e "
+poll_frequency_seconds=3
 
 # aero-test-util is in the same folder as this script
 source $( dirname $0 )/aero-test-util
@@ -19,13 +25,9 @@ function usage_()
     echo >&2
     echo "Search for subdirectories containing \"expected\" (and \"input\") files and submit these tests to the job queue" >&2
     echo >&2
-    echo "options" >&2
-    echo "    --path=<qstorage path>: q-storage directory; default: /mnt/q-storage" >&2
-    echo >&2
-    exit 1
 }
 
-# arguments: <filename> <path plan_to get>, e.g. "input" "plan/from"
+# arguments: <filename> <path plan to get>, e.g. "input" "plan/from"
 function extract_value()
 {
     local result=$( grep "^ *$2=" "$1" | sed 's/^[^=]*=//g' )
@@ -33,50 +35,86 @@ function extract_value()
     echo $result
 }
 
-# argument: <input file>
+# argument: <input file> <sequence number>
 function create_insert_statement()
 {
     local input_file=$1
+    local seq_num=$2
     local input=$( cat "$input_file" | sed 's/$/\\/g' | tr '\n' 'n' )   # all one line, newlines replaced with a literal "\n"
     local plan_from=$( extract_value "$input_file" "plan/from" )
     local plan_to=$( extract_value "$input_file" "plan/to" )
     local plan_time=$( extract_value "$input_file" "plan/departure_time" )
     if [[ -z "$plan_from" || -z "$plan_to" || -z "$plan_time" ]]; then return 1; fi  # error message already printed
-    local output_path="$output_base_dir/${plan_time}_$plan_from-$plan_to"
+    local output_path="$output_base_dir/${submit_time}_${seq_num}_${plan_from}-${plan_to}"
 
     # time format is like: "2014-01-23 12:34:56"
     local time_in_sql_format=$( echo $plan_time | awk '{ print substr($1, 1, 4) "-"  substr($1, 5, 2) "-" substr($1, 7, 2) " " substr($1, 10, 2) ":" substr($1, 12, 2) ":" substr($1, 14, 2); }' )
 
     echo "INSERT INTO JobQ (submitTime, task, JobQ.from, JobQ.to, takeoffTime, username, stdin, outputPath, build, priority)
 VALUES (now(), 'BUILDPLAN', '$plan_from', '$plan_to', '$time_in_sql_format', '$user_name', '$input', '$output_path',
-'$version_to_use', $task_priority);"
+'$build_to_use', $task_priority)"
 }
 
-path="--path=/mnt/q-storage"
-for arg in $@ ; do
-    if [[ "$arg" == "--help" || "$arg" == "-h" ]] ; then usage_ ; fi
-    if [[ "$arg" != "${arg#--path=}" ]] ; then path="$arg" ; fi
+# arguments: a list of job ids
+function wait_for_completion()
+{
+    remaining_jobs=$*
+    while sleep $poll_frequency_seconds; do
+        unfinished_jobs=
+        for job_id in $remaining_jobs; do
+            sql_to_execute="select status from JobQ where jobId = $job_id"
+            job_status=$( $sql_command "$sql_to_execute" | tail -1 )
+            if [[ "$job_status" == "DONE" ]]; then
+                echo "Job $job_id completed successfully -- checking expected results"
+                # TODO: call aero-test-match in the appropriate directory
+            elif [[ "$job_status" == "ERROR" ]]; then
+                echo "Job $job_id failed"
+            else
+                unfinished_jobs+=" $job_id"
+            fi
+        done
+        if [[ -z "$unfinished_jobs" ]]; then break; else remaining_jobs=$unfinished_jobs; fi
+    done
+}
+
+for arg in "$@" ; do
+    if [[ "$arg" == "--help" || "$arg" == "-h" ]] ; then usage_; exit 0
+    elif [[ "$arg" == -* ]]; then echo "$name: unrecognised option: $arg" >&2; exit 1
+    else echo "$name: unexpected argument: $arg" >&2; exit 1
+    fi
 done
 
 expected_files=$( find . -name "expected" )
 expected_files_count=$( find . -name "expected" | wc -l )
+job_id_list=()
 
 if (( $expected_files_count > 0 )) ; then
-    echo "$name: $expected_files_count test[s] in subdirectories of $( pwd )"
+    echo "$expected_files_count test[s] in subdirectories of $( pwd )"
     for e in $expected_files ; do
         basedir=$( pwd )
         cd $( dirname $e )
         if [[ ! -f "input" ]]; then
-            echo "$name: warning: \"expected\" but no \"input\" file in $( pwd )"
+            echo "Warning: found \"expected\" but no \"input\" file in $( pwd )"
         else
-            insert_statement=$( create_insert_statement "input" )
+            insert_statement=$( create_insert_statement "input" ${#job_id_list[@]} )
             if [[ $? == 0 ]]; then
-                echo "$name: adding plan_to job queue: $( readlink -e $e )"
-                echo $insert_statement
+                sql_to_execute="$insert_statement; SELECT LAST_INSERT_ID();"
+                job_id=$( $sql_command "$sql_to_execute" | tail -1 )
+                if [[ -z "$job_id" || "$job_id" == 0 ]]; then
+                    echo "$name: error executing SQL: $sql_to_execute; SELECT LAST_INSERT_ID();"
+                else
+                    job_id_list+=( $job_id )
+                    echo "Job $job_id: $( pwd )/input"
+                fi
             fi
         fi
         cd $basedir
     done
+    echo "${#job_id_list[@]} job(s) submitted"
+    if [[ ${#job_id_list[@]} != 0 ]]; then
+        echo; echo "Waiting for jobs to complete ..."
+        wait_for_completion ${job_id_list[@]}
+    fi
 else
     echo "$name: no \"expected\" files found in subdirectories of $( pwd )"
 fi
