aero-test-run: warn if "expected" file is missing (instead of running the test)

diff --git a/aero-test-run b/aero-test-run
--- a/aero-test-run
+++ b/aero-test-run
@@ -161,6 +161,7 @@ function stats_init()
 
 function stats_finalize()
 {
+    rm -f $timestamp_file
     if [[ -f $stats_progress_csv ]] ; then cat $stats_progress_csv | aero-progress --elapsed > $stats_elapsed_path_value ; fi
 }
 
@@ -218,15 +219,17 @@ if (( $test_scripts_count > 0 )) ; then
         if [[ -z "$test_exec" ]]; then echo "$name: error: no \"test\" file found in any parent directory of $dir" >&2 ; continue ; fi
         if [[ ! -x "$test_exec" ]]; then echo "$name: error: test is not executable: $test_exec" >&2 ; continue ; fi
         message_ "$name: test $count of $test_scripts_count: $dir: running..."
+        if [[ ! -f $dir/expected ]]; then echo "$name: missing \"expected\" file in $dir: skipping" >&2; continue; fi
         basedir=$( pwd )
         cd $dir
-        timestamp="$( mktemp -t aero-test-run-timestamp-$( basename $dir ).XXXXXX )" # capture starting time
-        touch "$timestamp"
+        timestamp_file="$( mktemp -t aero-test-run-timestamp-$( basename $dir ).XXXXXX )" # capture starting time
+        touch "$timestamp_file"
         if [ -f ./input ] ; then cat ./input ; fi \
             | aero_progress_named $stats_progress_csv "$dir" "$test_exec" $path $verbose 2> >( $grep_failed_ >&2 ) \
-            | if [ -f ./expected ] ; then aero-test-match ./expected 2>&1 | fail_on_output ; else cat > /dev/null ; fi
+            | aero-test-match ./expected 2>&1 \
+            | fail_on_output
         if status_ok ; then message_ "$name: test $count of $test_scripts_count: $dir: succeeded" ; else result=1 ; (( ++failed_count )) ; error_ "$name: $dir: failed" ; fi
-        report_leaked_shared "$timestamp" "$dir" # see if there are files in /dev/shm created past start_time and report
+        report_leaked_shared "$timestamp_file" "$dir" # see if there are files in /dev/shm created past start_time and report
         cd $basedir
         if [[ "$result" != 0 && "$until_first_failure" == true ]] ; then break ; fi
     done
