Remove the capability to run old-style tests (executable scripts in a directory called 'tests'). Update the usage notes.

diff --git a/aero-test-run b/aero-test-run
--- a/aero-test-run
+++ b/aero-test-run
@@ -6,13 +6,13 @@ function usage_()
 {
     echo -e "Usage: aero-test-run [<options>]" >&2
     echo >&2
-    echo -e "Search for and execute tests using two different methods (the second method is preferred):" >&2
+    echo -e "Searches for and executes tests under the current directory." >&2
     echo >&2
-    echo -e "(1) run all scripts in any subdirectories called 'tests'. A non-zero exit status indicates failure." >&2
-    echo >&2
-    echo -e "(2) find subdirectories containing the files 'test', 'input' or 'expected'. Execute 'test', then either:" >&2
+    echo -e "Finds subdirectories containing the files 'test', 'input' or 'expected'. Execute 'test', then either:" >&2
     echo -e "    (a) if 'expected' exists, compare its contents to the output of 'test' (\"path=value\" format)" >&2
-    echo -e "    (b) otherwise the success of the test depends on the exit status of 'test'." >&2
+    echo -e "    (b) otherwise the success of the test depends on the exit status of the 'test' script." >&2
+    echo >&2
+    echo -e "File 'input', if exists, is fed to the stdin of the test script." >&2
     echo >&2
     echo -e "If there is an 'input' or 'expected' file but no 'test' in the same directory, the 'test' script in the" >&2
     echo -e "closest parent directory is used. If there is a 'test' by itself with no 'input' or 'expected' file," >&2
@@ -26,11 +26,11 @@ function usage_()
     echo -e "    --debug: much more debug output" >&2
     echo -e "    --quiet,-q: output only failures" >&2
     echo -e "    --path=<qstorage path>: q-storage directory; default: /mnt/q-storage" >&2
-    echo -e "    --until-first-failure,-f: exit after the first failure" >&2
+    echo -e "    --until-first-failure,-f: exits after the first failure" >&2
     echo >&2
-    echo -e "Disabling tests" >&2
+    echo -e "Disabling tests:" >&2
     echo -e "    to disable tests in a directory and all its subdirectories" >&2
-    echo -e "    drop an empty file named ${brown}disabled${none} in that directory" >&2
+    echo -e "    create an empty file named ${brown}disabled${none} in that directory" >&2
     echo >&2
     exit 1
 }
@@ -190,38 +190,9 @@ trap "error_ 'aero-test-run: received signal, terminating...' >&2 ; is_shutdown=
 trap stats_finalize EXIT
 
 basedir=$( pwd )
-dirs=$( find . -name "tests" )
-dir_count=$( find . -name "tests" | wc -l )
 result=0
 
 stats_init
-
-if (( $dir_count > 0 )) ; then
-    message_ "$name: tests in $dir_count subdirectories of $basedir: running..."
-    for dir in $dirs ; do
-        tests=$( find $dir -name "*" -executable -type f )
-        tests_count=$( find $dir -name "*" -executable -type f | wc -l )
-        if disabled_ $dir ; then warning_ "$name: $dir: disabled" ; continue ; fi
-        message_ "$name: $tests_count test(s) in $dir: running..."
-        cd $dir
-        intermediate_result=0
-
-        for t in $tests ; do
-            if [[ -n "$is_shutdown" ]] ; then error_ "aero-test-run: terminated" >&2 ; exit 1 ; fi
-            message_ "$name: $t: running..."
-            timestamp="$( mktemp -t aero-test-run-timestamp-$(basename $t).XXXXXX )" # capture starting time
-            touch "$timestamp"
-            aero_progress_named $stats_progress_csv "$t" ./$( basename $t ) $path $debug 2> >( $grep_failed_ >&2 )
-            if status_ok ; then message_ "$name: $t: succeeded" ; else intermediate_result=1; result=1 ; error_ "$name: $t: failed" ; fi
-            report_leaked_shared "$timestamp" "$t" # see if there are files in /dev/shm created past start_time and report
-            if [[ "$result" != 0 && "$until_first_failure" == true ]] ; then break ; fi
-        done
-        cd $basedir
-        if [[ "$result" != 0 && "$until_first_failure" == true ]] ; then break ; fi
-        if [[ "$intermediate_result" == 0 ]] ; then message_ "$name: $tests_count test(s) in $dir: succeeded" ; else error_ "$name: tests in $tests_count test(s) in $dir...: some tests failed" ; fi
-    done
-    if [[ "$result" == 0 ]] ; then message_ "$name: tests in $dir_count subdirectories of $basedir: succeeded" ; else error_ "$name: tests in $dir_count directories: some tests failed" ; fi
-fi
 
 # search for directories containing either "test", "input" or "expected";
 # if "test" is absent, use the "test" in the closest parent directory
@@ -256,7 +227,7 @@ if (( $test_scripts_count > 0 )) ; then
     done
     if [[ "$result" == 0 ]] ; then message_ "$name: in subdirectories of $( pwd ): succeeded" ; else error_ "$name: $test_scripts_count test[s] in subdirectories of $( pwd ): $failed_count test[s] out of $test_scripts_count failed" ; fi
 fi
-if (( $test_scripts_count == 0 && $dir_count == 0 )) ; then echo -e "${brown}$name: warning: no tests or test directories found in $( pwd )${none}" >&2 ; fi
+if (( $test_scripts_count == 0 )) ; then echo -e "${brown}$name: warning: no tests found in $( pwd )${none}" >&2 ; fi
 
 exit $result
 
