aero-test-run: added calculation of elapsed time for each test

diff --git a/aero-test-run b/aero-test-run
--- a/aero-test-run
+++ b/aero-test-run
@@ -150,12 +150,30 @@ function report_leaked_shared()
     rm -f "$timestamp"
 }
 
+function stats_init()
+{
+    stats="$(pwd)/stats"
+    stats_progress_csv="$stats/progress.csv"
+    stats_elapsed_path_value="$stats/elapsed.csv"
+    rm -rf $stats
+    mkdir $stats
+}
+
+function stats_finalize()
+{
+    cat $stats_progress_csv | aero-progress --elapsed > $stats_elapsed_path_value
+}
+
 trap "error_ 'aero-test-run: received signal, terminating...' >&2 ; is_shutdown=true" SIGINT SIGTERM
+trap stats_finalize EXIT
 
 basedir=$( pwd )
 dirs=$( find . -name "tests" )
 dir_count=$( find . -name "tests" | wc -l )
 result=0
+
+stats_init
+
 if (( $dir_count > 0 )) ; then
     message_ "$name: tests in $dir_count subdirectories of $basedir: running..."
     for dir in $dirs ; do
@@ -170,7 +188,7 @@ if (( $dir_count > 0 )) ; then
             message_ "$name: $t: running..."
             timestamp="$( mktemp -t aero-test-run-timestamp-$(basename $t).XXXXXX )" # capture starting time
             touch "$timestamp"
-            ./$( basename $t ) $path $debug 2> >( $grep_failed_ >&2 )
+            aero_progress_named $stats_progress_csv "$t" ./$( basename $t ) $path $debug 2> >( $grep_failed_ >&2 )
             if status_ok ; then message_ "$name: $t: succeeded" ; else intermediate_result=1; result=1 ; error_ "$name: $t: failed" ; fi
             report_leaked_shared "$timestamp" "$t" # see if there are files in /dev/shm created past start_time and report
             if [[ "$result" != 0 && "$until_first_failure" == true ]] ; then break ; fi
@@ -195,31 +213,26 @@ if (( $test_scripts_count > 0 )) ; then
         if [[ -n "$is_shutdown" ]] ; then error_ "aero-test-run: terminated" >&2 ; exit 1 ; fi
         if disabled_ $dir ; then warning_ "$name: $dir: disabled" ; continue ; fi
         test_exec=$( closest_file_in_path "$dir" "test" )
-        if [[ -z "$test_exec" ]]; then
-            echo "$name: error: no \"test\" file found in any parent directory of $dir" >&2
-        elif [[ ! -x "$test_exec" ]]; then
-            echo "$name: error: test is not executable: $test_exec" >&2
-        else
-            message_ "$name: $dir: running..."
-            basedir=$( pwd )
-            cd $dir
-            timestamp="$( mktemp -t aero-test-run-timestamp-$(basename $dir).XXXXXX )" # capture starting time
-            touch "$timestamp"
-            if [ -f ./input ] ; then cat ./input ; fi \
-                | "$test_exec" $path $verbose 2> >( $grep_failed_ >&2 ) \
-                | if [ -f ./expected ] ; then aero-test-match ./expected 2>&1 | fail_on_output ; else cat > /dev/null ; fi
-            if status_ok ; then message_ "$name: $dir: succeeded" ; else result=1 ; (( ++failed_count )) ; error_ "$name: $dir: failed" ; fi
-            # see if there are files in /dev/shm created past start_time and report
-            report_leaked_shared "$timestamp" "$dir"
-            cd $basedir
-            if [[ "$result" != 0 && "$until_first_failure" == true ]] ; then break ; fi
-        fi
+        if [[ -z "$test_exec" ]]; then echo "$name: error: no \"test\" file found in any parent directory of $dir" >&2 ; continue ; fi
+        if [[ ! -x "$test_exec" ]]; then echo "$name: error: test is not executable: $test_exec" >&2 ; continue ; fi
+        message_ "$name: $dir: running..."
+        basedir=$( pwd )
+        cd $dir
+        timestamp="$( mktemp -t aero-test-run-timestamp-$(basename $dir).XXXXXX )" # capture starting time
+        touch "$timestamp"
+        if [ -f ./input ] ; then cat ./input ; fi \
+            | aero_progress_named $stats_progress_csv "$dir" "$test_exec" $path $verbose 2> >( $grep_failed_ >&2 ) \
+            | if [ -f ./expected ] ; then aero-test-match ./expected 2>&1 | fail_on_output ; else cat > /dev/null ; fi
+        if status_ok ; then message_ "$name: $dir: succeeded" ; else result=1 ; (( ++failed_count )) ; error_ "$name: $dir: failed" ; fi
+        report_leaked_shared "$timestamp" "$dir" # see if there are files in /dev/shm created past start_time and report
+        cd $basedir
+        if [[ "$result" != 0 && "$until_first_failure" == true ]] ; then break ; fi
     done
     if [[ "$result" == 0 ]] ; then message_ "$name: in subdirectories of $( pwd ): succeeded" ; else error_ "$name: $test_scripts_count test[s] in subdirectories of $( pwd ): $failed_count test[s] out of $test_scripts_count failed" ; fi
 fi
 if (( $test_scripts_count == 0 && $dir_count == 0 )) ; then echo -e "${brown}$name: warning: no tests or test directories found in $( pwd )${none}" >&2 ; fi
-exit $result
 
+exit $result
 
 # for batch modification of test cases
 # for file in `find -name "expected"` ; do
