Use the aero-test-sql-util facilities to configure JobQ-related scripts. All three can take a configuration file redirecting mysql command to a custom database.

diff --git a/aero-test-status b/aero-test-status
--- a/aero-test-status
+++ b/aero-test-status
@@ -2,34 +2,44 @@
 
 name=$( basename $0 )
 
+# defaults can be overridden through config
 db_host="129.78.214.114"
 db_port="3306"
 db_user="jobq_submit"
 db_pwd="bReWAca4rUJu"
 db_name="qdata"
-sql_command="mysql -h $db_host -P $db_port -u $db_user -p$db_pwd $db_name -e "
+all_db_vars="db_host,db_port,db_user,db_pwd,db_name"
 
-# aero-test-util is in the same folder as this script
+# aero-test-[sql-]util are in the same folder as this script
+source $( which comma-application-util )
 source $( dirname $0 )/aero-test-util
+source $( dirname $0 )/aero-test-sql-util
 
 function usage()
 {
-    echo "Usage: $name [<batch id>]" >&2
+    echo "Usage: $name [<batch id>] [--config=<config file>]" >&2
     echo >&2
-    echo "Get the status of tests that were run using aero-test-submit. If a <batch id> is missing, the most recent id is used."
+    echo "Get the status of tests that were run using aero-test-submit." >&2
+    echo "If a <batch id> is missing, the most recent id is used." >&2
+    echo "Convig allows to override the default sql settings." >&2
     echo >&2
 }
 
 batch_id=
+config_file=""
 
 for arg in "$@"; do
     case $arg in
-        -h|--help) usage; exit 0;;
-        -*)        echo "$name: unknown option '$arg'" >&2; exit 1;;
-        *)         if [[ -z "$batch_id" ]]; then batch_id=$arg
-                   else echo "$name: unexpected argument '$arg'" >&2; exit 1; fi;;
+        -h|--help)    usage; exit 0;;
+        --config=*)   config_file=${arg#*=};;
+        -*)           echo "$name: unknown option '$arg'" >&2; exit 1;;
+        *)            if [[ -z "$batch_id" ]]; then batch_id=$arg
+                      else echo "$name: unexpected argument '$arg'" >&2; exit 1; fi;;
     esac
 done
+
+if [ -n "$config_file" ] ; then sql_read_config "$config_file" "$all_db_vars" || exit 1 ; fi
+sql_command=$( sql_get_command )
 
 if [[ -z "$batch_id" ]]; then
     batch_id=$( $sql_command "select max(batchId) from JobQ" | tail -1 )
diff --git a/aero-test-submit b/aero-test-submit
--- a/aero-test-submit
+++ b/aero-test-submit
@@ -3,6 +3,7 @@
 name=$( basename $0 )
 
 submit_time=$( date --utc "+%Y%m%dT%H%M%S" )
+# defaults can be overridden through config
 output_base_dir="/var/qantas/data/log/gui/acceptance"
 user_name="acceptance"
 build_to_use="prod"   # "prod", "test" or "bleeding"
@@ -12,21 +13,25 @@ db_port="3306"
 db_user="jobq_submit"
 db_pwd="bReWAca4rUJu"
 db_name="qdata"
-sql_command="mysql -h $db_host -P $db_port -u $db_user -p$db_pwd $db_name -e "
+all_db_vars="output_base_dir,user_name,build_to_use,task_priority,db_host,db_port,db_user,db_pwd,db_name"
 
-# aero-test-util is in the same folder as this script
-. $( which aero-test-util )
+# aero-test-[sql-]util are in the same folder as this script
+source $( which comma-application-util )
+source $( dirname $0 )/aero-test-util
+source $( dirname $0 )/aero-test-sql-util
 
 function usage_()
 {
 cat <<EOF >&2
-Usage: $name [-h|--help] [--build|-b=prod|test|bleeding]
+Usage: $name [-h|--help] [--build|-b=prod|test|bleeding] [--config=<config file>]
 
 Search for subdirectories containing \"input\" files and submit these tests to the job queue.
 
 Options:
 
     --build|-b=     Specify which build to use ("prod", "test" or "bleeding", default "$build_to_use")
+    --config=       Provide a configuration file in name=value format; possible input fields
+                    are ${all_db_vars/,/ }
 
 EOF
 }
@@ -66,14 +71,21 @@ VALUES (now(), $batch_id, 'BUILDPLAN', '$plan_from', '$plan_to', '$time_in_sql_f
 '$build_to_use', $task_priority)"
 }
 
+config_file=""
 for arg in "$@"; do
     case $arg in
         -h|--help)      usage_; exit 0;;
         -b=*|--build=*) build_to_use=${arg#*=};;
+        --config=*)     config_file=${arg#*=}
+                        if [ ! -f "$config_file" ] ; then echo "$name: config file '$config_file' not found" >&2; exit 1; fi
+                        ;;
         -*)             echo "$name: unrecognised option: $arg" >&2; exit 1;;
         *)              echo "$name: unexpected argument: $arg" >&2; exit 1;;
     esac
 done
+
+if [ -n "$config_file" ] ; then sql_read_config "$config_file" "$all_db_vars" || exit 1 ; fi
+sql_command=$( sql_get_command )
 
 case "$build_to_use" in
     prod|test|bleeding) ;;
