aero-test-match: check for empty input (so when a flight plan fails, there is just one error message instead of many)

diff --git a/aero-test-match b/aero-test-match
--- a/aero-test-match
+++ b/aero-test-match
@@ -51,6 +51,14 @@ done
 if [[ -z "$expr_file" ]]; then echo "$name: missing required argument <expected-values-file>" >&2; exit 1; fi
 
 # if the variables file name is known, pass it to name-value-eval, since it can appear in some error messages
-if [[ -z "$variables" ]]; then name-value-eval --test "$expr_file"
-else name-value-eval --test "$expr_file" --variables="$variables"; fi
+if [[ -z "$variables" ]]; then
+    input="$( cat )"
+    if [[ -z "$input" ]]; then echo "$name: error: empty input (flight plan failed?)" >&2; exit 1; fi
+    echo "$input" | name-value-eval --test "$expr_file"
+else
+    if [[ ! -f "$variables" || ! -s "$variables" ]]; then
+        echo "$name: error: empty or non-existent input file '$variables' (flight plan failed?)" >&2; exit 1
+    fi
+    name-value-eval --test "$expr_file" --variables="$variables"
+fi
 
