Bug-fix: a race condition observed when verification is done and SIGCONT is sent before the child process even stopped itself with SIGSTOP, resulting in the child hanging up forever. Poll children until they stopped themselves.

diff --git a/util b/util
--- a/util
+++ b/util
@@ -46,16 +46,28 @@ function background_launcher()
 export -f background_launcher
 declare -r background_launcher
 
-function wake_up()
+function wake_up_listed()
 {
-    local pid
+    local pid stat
+    # one possible issue is that verification can finish before background processes
+    # even send STOP to themselves; in such a case, they may receive STOP after CONT
+    # causing the processes to hang indefinitely
+    # therefore, make sure that the process is in stopped state (T) before signalling
     for pid in "$@" ; do
-        echo "waking up '$pid'" >&2
-        kill -s CONT $pid
+        builtin echo "$FUNCNAME: handle process '$pid'" >&2
+        while true ; do
+            stat=$( ps --no-headers -o stat --pid $pid ) # calling ps is already a delay; do not sleep
+            stat=${stat:0:1} # discard additional BSD characters
+            [[ "$stat" == "T" ]] && break
+            [[ -z "$stat" ]] && { builtin echo "$FUNCNAME: process '$pid' not found, skip" >&2; break; }
+            builtin echo "$FUNCNAME: process '$pid' is not stopped yet, try again" >&2
+        done
+        [[ "$stat" == "T" ]] && builtin kill -s CONT $pid
     done
+    return 0
 }
-export -f wake_up
-declare -r wake_up
+export -f wake_up_listed
+declare -r wake_up_listed
 
 function wake_up_dead()
 {
