Overlapping in time is not the same as running at once (overlap with one test at start and another at the end does not mean all three are running at once). The test logic was broken. Re-factor and use resource counter explicitly.

diff --git a/util/test/test_run/resources/test b/util/test/test_run/resources/test
--- a/util/test/test_run/resources/test
+++ b/util/test/test_run/resources/test
@@ -1,6 +1,9 @@
 #!/bin/bash
 
-name=$( basename $0 )
+scriptname=$( basename $0 )
+
+source $( which comma-process-util ) || exit 1
+source $( which comma-application-util ) || exit 1
 
 function handle()
 {
@@ -9,28 +12,48 @@ function handle()
 
 trap 'handle' EXIT
 
-output_dir="output"
-mkdir -p "$output_dir" || exit 1
-output_dir=$( readlink -f "$output_dir" )
-
 tarball="../data/resources.tar"
 [[ -r "$tarball" ]] || {
-    echo "$name: file '$tarball' not found" >&2
+    echo "$scriptname: file '$tarball' not found" >&2
     exit 1
 }
 tarball=$( readlink -f "$tarball" )
+
+export output_dir="output"
+mkdir -p "$output_dir" || exit 1
+output_dir=$( readlink -f "$output_dir" )
 
 workdir=$( mktemp --directory --tmpdir="$output_dir" )
 cd "$workdir"
 tar xf "$tarball" || exit 1
 cd resources || exit 1
 
-comma-test-run --raw --max-memory-main=5000 --max-memory-shared=6000 --max-parallel=10 > "$output_dir/comma-test-run.log"
-(( $? == 0 )) || exit 1
+function run_comma_test_run()
+{
+    comma-test-run --raw --max-memory-main=5000 --max-memory-shared=6000 --max-parallel=10 > "$output_dir/comma-test-run.log"
+}
+export -f run_comma_test_run
 
-cat "stats/progress.csv" \
-    | csv-time --fields=time,, --to seconds \
-    | csv-shuffle --fields=time,name,stage --output-fields=name,stage,time \
-    | sed 's@^./@@' \
-    | name-value-from-csv number,stage,time --indices=number,stage --no-brackets --prefix=test \
-    | sed 's@/@[@;s@/@]/@;s@"@@g'  # want to bracket number but not stage; no quotes
+function monitor_users()
+{
+    local counter max_cpus cpus iter
+    local max_iter=$1
+    max_cpus=0
+    iter=0
+    while true ; do
+        sleep 1
+        counter=$( find . -name resources_counter.json )
+        [[ -f "$counter" ]] && {
+            cpus=$( cat "$counter" | name-value-get --from json resources/cpus ; comma_status_ok && exit 0 || exit 1 )
+            (( $? == 0 )) && {
+                (( cpus > max_cpus )) && max_cpus=$cpus
+            }
+        }
+        (( ++iter ))
+        (( iter > max_iter )) && break
+    done
+    echo "cpus/max=$max_cpus"
+}
+export -f monitor_users
+
+comma_execute_and_wait --group "bash -c monitor_users 25" "bash -c run_comma_test_run"
