csv-bin-cat: make unit tests to use canned data; data generation took a few seconds each time.

diff --git a/csv/test/csv-bin-cat/multiple/test b/csv/test/csv-bin-cat/multiple/test
--- a/csv/test/csv-bin-cat/multiple/test
+++ b/csv/test/csv-bin-cat/multiple/test
@@ -1,32 +1,21 @@
 #!/bin/bash
 
-function generate_binary_file()
-{
-    local max=$1
-    local t
-    for i in $( seq 0 $(( max - 1 )) ) ; do
-        t=$( date +%Y%m%dT%H%M%S.%N )
-        echo "$i,$t,your-data-could-be-here-${n}"
-        sleep 0.22
-    done \
-        | csv-paste --size=5 line-number - \
-        | csv-paste --size=2 - line-number \
-        | csv-to-bin "ui,ui,t,s[100],ui"
-}
+scriptname=$( basename "$0" )
+
+source $( which comma-application-util ) || { echo "$scriptname: cannot source 'comma-application-util'" >&2; exit 1; }
 
 output_dir="output"
-mkdir -p "$output_dir" || exit 1
-cd "$output_dir"
+mkdir -p "$output_dir" || { echo "$scriptname: cannot create directory '$output_dir'" >&2; exit 1; }
 
-for n in $( seq 0 2 ) ; do
-    generate_binary_file 10 > "file${n}.bin"
-done
+comma_path_value_to_var
+
+cd "$output_dir"
 
 cmd="--binary=2ui,t,s[100],ui --fields=block,counter,t,string,num --output-fields=t"
 subdir=0
-mkdir -p "$subdir" || exit 1
-csv-bin-cat "file0.bin" "file1.bin" "file2.bin" $cmd > "$subdir/new.bin"
-cat "file0.bin" "file1.bin" "file2.bin" | csv-shuffle $cmd > "$subdir/old.bin"
+mkdir -p "$subdir" || { echo "$scriptname: cannot create directory '$output_dir/$subdir'" >&2; exit 1; }
+csv-bin-cat $input_files $cmd > "$subdir/new.bin"
+cat $input_files | csv-shuffle $cmd > "$subdir/old.bin"
 cmp "$subdir/new.bin" "$subdir/old.bin" > "$subdir/cmp.log"
 echo "test[$subdir]/cmp/status=$?"
 
@@ -35,7 +24,7 @@ record=$( csv-size "2ui,t,s[100],ui" )
 for count in nan -1 0 4 15 ; do
     for skip in 6 12 23 ; do
         (( ++subdir ))
-        mkdir -p "$subdir" || exit 1
+        mkdir -p "$subdir" || { echo "$scriptname: cannot create directory '$output_dir/$subdir'" >&2; exit 1; }
         car="cat"
         cdr="tail -c +$(( record * skip + 1 ))"
         count_option=
@@ -43,8 +32,8 @@ for count in nan -1 0 4 15 ; do
             count_option="--count=$count"
             (( count >= 0 )) && car="head -c $(( record * count ))"
         }
-        csv-bin-cat "file0.bin" "file1.bin" "file2.bin" $cmd --skip=$skip $count_option > "$subdir/new.bin"
-        cat "file0.bin" "file1.bin" "file2.bin" | $cdr | $car | csv-shuffle $cmd > "$subdir/old.bin"
+        csv-bin-cat $input_files $cmd --skip=$skip $count_option > "$subdir/new.bin"
+        cat $input_files | $cdr | $car | csv-shuffle $cmd > "$subdir/old.bin"
         cmp "$subdir/new.bin" "$subdir/old.bin" > "$subdir/cmp.log"
         echo "test[$subdir]/cmp/status=$?"
         echo "test[$subdir]/skip=$skip"
diff --git a/csv/test/csv-bin-cat/single/test b/csv/test/csv-bin-cat/single/test
--- a/csv/test/csv-bin-cat/single/test
+++ b/csv/test/csv-bin-cat/single/test
@@ -1,33 +1,21 @@
 #!/bin/bash
 
-function generate_binary_file()
-{
-    local max=$1
-    local t
-    for i in $( seq 0 $(( max - 1 )) ) ; do
-        t=$( date +%Y%m%dT%H%M%S.%N )
-        echo "$i,$t,your-data-could-be-here-${n}"
-        sleep 0.22
-    done \
-        | csv-paste --size=5 line-number - \
-        | csv-paste --size=2 - line-number \
-        | csv-to-bin "ui,ui,t,s[100],ui"
-}
+scriptname=$( basename "$0" )
+
+source $( which comma-application-util ) || { echo "$scriptname: cannot source 'comma-application-util'" >&2; exit 1; }
 
 output_dir="output"
-mkdir -p "$output_dir" || exit 1
+mkdir -p "$output_dir" || { echo "$scriptname: cannot create directory '$output_dir'" >&2; exit 1; }
 
-binfile="$output_dir/file.bin"
-
-generate_binary_file 10 > "$binfile"
+comma_path_value_to_var
 
 function compare()
 {
     local cmd="$1"
     local subdir="$2"
-    mkdir -p "$output_dir/$subdir"
-    csv-bin-cat "$binfile" $cmd > "$output_dir/$subdir/new.bin"
-    cat "$binfile" | csv-shuffle $cmd > "$output_dir/$subdir/old.bin"
+    mkdir -p "$output_dir/$subdir" || { echo "$scriptname: cannot create directory '$output_dir/$subdir'" >&2; exit 1; }
+    csv-bin-cat "$input_files" $cmd > "$output_dir/$subdir/new.bin"
+    cat "$input_files" | csv-shuffle $cmd > "$output_dir/$subdir/old.bin"
     cmp "$output_dir/$subdir/new.bin" "$output_dir/$subdir/old.bin" > "$output_dir/$subdir/cmp.log"
 }
 
