comma-launchpad-upload: minor fix

diff --git a/system/launchpad/comma-launchpad-upload b/system/launchpad/comma-launchpad-upload
--- a/system/launchpad/comma-launchpad-upload
+++ b/system/launchpad/comma-launchpad-upload
@@ -20,10 +20,10 @@ name=comma_${comma_version}
 if [[ "$what" == "orig" ]]; then
     rm -f comma/debian/files
     tar -acf $name.orig.tar.gz comma || die "tar failed"
-    ( cd comma && debuild -S -sa ) || die "debuild failed"
+    ( cd comma && debuild -S -sa -d ) || die "debuild failed"
     dput ppa:orthographic/comma $name-0ppa0_source.changes || die "dput failed"
 elif [[ "$what" == "update" ]]; then
-    ( cd comma && debuild -S -sd ) || die "debuild failed"
+    ( cd comma && debuild -S -sd -d ) || die "debuild failed"
     dput ppa:orthographic/comma $name-0ppa0_source.changes || die "dput failed"
 else
     die "expected <what>: orig or update; got \"$what\""
