comma-launchpad-upload: brushed up; bug fixed

diff --git a/system/launchpad/comma-launchpad-upload b/system/launchpad/comma-launchpad-upload
--- a/system/launchpad/comma-launchpad-upload
+++ b/system/launchpad/comma-launchpad-upload
@@ -5,11 +5,11 @@
 #     - update changelog
 #       - version
 #       - changes
-#     - update default version in cmake
-#     - tag repo with version
+#       - date
+#     - cmake: update default version
 #     - commit
+#     - tag repo with version
 #     - push
-#   ? check current version at launchpad
 
 function say() { echo "usage: $0: $@" >&2; }; function die() { say "$@"; exit 1; }
 [[ -n "$2" ]] || { echo "usage: $0 <what> <ubuntu-name> <comma-version>" >&2; exit 1; }
@@ -17,14 +17,9 @@ what=$1
 comma_version=$2
 name=comma_${comma_version}
 [[ -d comma ]] || die "comma directory not found; please run in something like ~/src"
-if [[ "$what" == "orig" ]]; then
-    rm -f comma/debian/files
-    tar -acf $name.orig.tar.gz comma || die "tar failed"
-    ( cd comma && debuild -S -sa -d ) || die "debuild failed"
-    dput ppa:orthographic/comma $name-0ppa0_source.changes || die "dput failed"
-elif [[ "$what" == "update" ]]; then
-    ( cd comma && debuild -S -sd -d ) || die "debuild failed"
-    dput ppa:orthographic/comma $name-0ppa0_source.changes || die "dput failed"
-else
-    die "expected <what>: orig or update; got \"$what\""
-fi
+tar -acf $name.orig.tar.gz comma || die "tar failed"
+if [[ "$what" == "orig" ]]; then rm -f comma/debian/files; what_option='a'
+elif [[ "$what" == "update" ]]; then what_option='d'
+else die "expected <what>: orig or update; got \"$what\""; fi
+( cd comma && debuild -S -s$what_option ) || die "debuild failed"
+dput ppa:orthographic/comma $name-0ppa0_source.changes || die "dput failed"
