Brush up the comments to tests and capture more output to ensure all is working.

diff --git a/application/test/execute_and_wait/basic/test b/application/test/execute_and_wait/basic/test
--- a/application/test/execute_and_wait/basic/test
+++ b/application/test/execute_and_wait/basic/test
@@ -2,64 +2,60 @@
 
 source $( which comma-application-util ) || exit 1
 
+function grab()
+{
+    sed --regexp-extended -n 's@.*(normal exit).*@\1@p'
+}
+export -f grab
+
 export output_dir="output"
 rm -rf "$output_dir" || exit 1
 mkdir -p "$output_dir" || exit 1
 
-# Tests to consider:
-#
-# - run a verbose utility like "comma-nap" to completion
-#   verify that the test program indeed was executed
-# - same with a bash function
-# - same with passing arguments and variables to a bash function
-#
-# - run comma-nap and terminate by timeout; verify that the command-to-execute
-#   was terminated, and that that expected status is returned
-# - run comma-nap and kill comma_execute_and_wait; verify that command being
-#   executed is killed, and that the expected exit status is returned
-#
-# - set up handlers, then run comma_execute_and_wait, and kill by a signal;
-#   verify that control is returned to the original handler
-#
-# - specify different signal list: trap a custom signal and report
-
+# run a verbose utility to completion; check that all went smoothly
+# and the test program indeed was executed
 function test01()
 {
-    comma_execute_and_wait "comma-nap 10" >/dev/null
+    comma_execute_and_wait "comma-nap 10" > "$output_dir/test01.log"
 }
+test01 ; echo "test[1]/exit/status=$?" ; echo "test[1]/output=\""$( tail -n 1 "$output_dir"/test01.log | grab )"\""
 
+# run a long program and terminate by timeout; verify that the command-to-execute
+# was terminated (did not produce output), and that that expected status was returned
 function test02()
 {
-    comma_execute_and_wait --max-wait=5 "comma-nap 10" >/dev/null
+    comma_execute_and_wait --max-wait=5 "comma-nap 10" > "$output_dir/test02.log"
 }
+test02 ; echo "test[2]/exit/status=$?" ; echo "test[2]/output=\""$( tail -n 1 "$output_dir"/test02.log )"\""
 
+# check that can parse arguments to '--signals' (only parsed, not used)
 function test03()
 {
-    comma_execute_and_wait --signals="TERM,USR1" "comma-nap 10" >/dev/null
+    comma_execute_and_wait --signals="TERM,USR1" "comma-nap 10" > "$output_dir/test03.log"
 }
+test03 ; echo "test[3]/exit/status=$?" ; echo "test[3]/output=\""$( tail -n 1 "$output_dir"/test03.log | grab )"\""
 
-function test04_to_execute()
+# check that can run a bash function to completion and pass arguments through
+# the environment
+function function_to_execute()
 {
     { comma-nap $nap_time && echo "OK" ; } > $output_file
 }
-export -f test04_to_execute
+export -f function_to_execute
 
 function test04()
 {
     export output_file="$output_dir/test04.log"
     export nap_time=5
-    comma_execute_and_wait "bash -c test04_to_execute" >/dev/null
+    comma_execute_and_wait "bash -c function_to_execute" >/dev/null
 }
+test04 ; echo "test[4]/exit/status=$?" ; echo "test[4]/output=\""$( tail -n 1 "$output_dir"/test04.log )"\""
 
+# run a long bash function and terminate early; check the exit status and lack of output
 function test05()
 {
     export output_file="$output_dir/test05.log"
     export nap_time=10
-    comma_execute_and_wait --timeout=5 "bash -c test04_to_execute" >/dev/null
+    comma_execute_and_wait --timeout=5 "bash -c function_to_execute" >/dev/null
 }
-
-test01 ; echo "test[1]/exit/status=$?"
-test02 ; echo "test[2]/exit/status=$?"
-test03 ; echo "test[3]/exit/status=$?"
-test04 ; echo "test[4]/exit/status=$?" ; echo "test[4]/output=\""$( tail -n 1 "$output_dir"/test04.log )"\""
 test05 ; echo "test[5]/exit/status=$?" ; echo "test[5]/output=\""$( tail -n 1 "$output_dir"/test05.log )"\""
