Start splitting the two implementations (pid-fifo and stop-start) into directories of their own.

diff --git a/pid_fifo/tests/basic/failure/test b/pid_fifo/tests/basic/failure/test
--- a/pid_fifo/tests/basic/failure/test
+++ b/pid_fifo/tests/basic/failure/test
@@ -3,16 +3,16 @@
 readonly scriptname=$( basename "$0" )
 
 util="../../../pid-fifo-util"
-source "$util" || { echo "cannot source '$util'" >&2; exit 1; }
+source "$util" || { echo "$scriptname: cannot source '$util'" >&2; exit 1; }
+
+main_pid=$BASHPID
+echo "$scriptname: running as PID $main_pid" >&2
 
 function report_own_tree()
 {
-    echo "process tree of main:"
+    echo "$scriptname: process tree of main:"
     pstree -a -c -g -l -p $main_pid
 }
-
-export main_pid=$BASHPID
-echo "main is PID $main_pid" >&2
 
 fifo=$( mktemp --dry-run )
 trap "rm -f '$fifo'" EXIT
@@ -20,15 +20,25 @@ mkfifo "$fifo" || { echo "$scriptname: cannot create FIFO '$fifo'" >&2; exit 1; 
 echo "$scriptname: use fifo '$fifo'" >&2
 
 children=()
-for n in {1..3} ; do
+child_count=3
+bad_boy=111
+echo "bad/boy=$bad_boy"
+echo "child/count=$child_count"
+for i in $( eval echo "{1..$child_count}" ) ; do
     builtin echo "$scriptname: attempt to start a background process..." >&2
+    # break the logic
+    echo $bad_boy > "$fifo" &
     background_launcher "$fifo" sleep 1 & last_child=$!
+    echo "child[$i]/pid=$last_child"
     builtin echo "$scriptname: launched background child '$last_child', now verify..." >&2
-    verify_background_process_id "$fifo" $last_child || { pkill --signal TERM -P $main_pid; wait; exit 1; }
+    verify_background_process_id "$fifo" $last_child
+    echo "child[$i]/verification/status=$?"
     children+=( $last_child )
 done
 
 report_own_tree >&2
 
 echo "waiting for the children to terminate..." >&2
+# this is needed in case of failures so that the writers (background processes) do not block
+cat < "$fifo" >/dev/null
 wait
