Remove the annoying "Permission denied" messages from comma-resources-util (produced by df when it does not have permissions).

diff --git a/util/comma-resources-util b/util/comma-resources-util
--- a/util/comma-resources-util
+++ b/util/comma-resources-util
@@ -141,13 +141,14 @@ function comma_total_system_resources()
     local cpus memory_main memory_shared memory_limits
     local name="comma_total_system_resources"
     cpus=$( grep -c '^processor' /proc/cpuinfo )
-    (( $? == 0 || $cpus > 0 )) || { echo "$name: cannot grep '/proc/cpuinfo' for the number of processors" >&2; return 1; }
+    (( $? == 0 && $cpus > 0 )) || { echo "$name: cannot grep '/proc/cpuinfo' for the number of processors" >&2; return 1; }
     #
     # ipcs -ml was found to return weird values on many systems
-    memory_shared=$( df --block-size=1 --local | grep '/shm$' | awk '{ print $2 }' )
+    memory_shared=$( df --block-size=1 --local 2>&1 | grep -v ": Permission denied" | grep '/shm$' | awk '{ print $2 }' )
+    (( $? == 0 && $memory_shared > 0 )) || { echo "$name: cannot determine shared memory size" >&2; return 1; }
     #
     memory_main=$( cat /proc/meminfo | sed -n --regexp-extended "s/^MemTotal: *(.*) .*$/\1/p" )
-    (( $memory_main > 0 )) || { echo "$name: cannot determine total memory size" >&2; exit 1; }
+    (( $? == 0 && $memory_main > 0 )) || { echo "$name: cannot determine total memory size" >&2; exit 1; }
     memory_main=$(( $memory_main * 1024 ))
     #
     echo "resources/cpus=\"$cpus\""
