Start work on parallel tests. Provide a first draft function to execute a test in a separate (background, in this case) process.

diff --git a/util/comma-test-run b/util/comma-test-run
--- a/util/comma-test-run
+++ b/util/comma-test-run
@@ -59,22 +59,25 @@ function error_()
     echo -e "$high$1$normal" >&2
     tput sgr0
 }
+export -f error_
 
 function message_()
 {
     if [[ "$quiet" != "true" ]] ; then tput bold ; echo $1 >&2 ; tput sgr0 ; fi
 }
+export -f message_
 
 function dump_file_()
 {
     if [[ "$quiet" != "true" ]] ; then cat "$1" >&2 ; fi
 }
-
+export -f dump_file_
 
 function warning_()
 {
     if [[ "$quiet" != "true" ]] ; then tput bold ; echo -e "${brown}$1${none}" >&2  ; tput sgr0 ; fi
 }
+export -f warning_
 
 function disabled_()
 {
@@ -90,6 +93,7 @@ function fail_on_output()
 {
     if grep "."; then return 1; else return 0; fi
 }
+export -f fail_on_output
 
 # return a string with "\" before any characters that are special in regular expressions
 function escape_special_chars()
@@ -159,6 +163,7 @@ function stats_init()
     stats_elapsed_path_value="$stats/elapsed.csv"
     rm -rf $stats
     mkdir $stats
+    touch "$stats_progress_csv"
 }
 
 function stats_finalize()
@@ -166,13 +171,75 @@ function stats_finalize()
     if [[ -f $stats_progress_csv ]] ; then cat $stats_progress_csv | comma-progress --elapsed > $stats_elapsed_path_value ; fi
 }
 
+# to run tests in parallel, we need to lock stats_progress_csv and/or stdout/stderr
+# this is the global flock name
+comma_test_run_flock=$( mktemp )
+export comma_test_run_flock
+
 trap "error_ 'comma-test-run: received signal, terminating...' >&2 ; is_shutdown=true" SIGINT SIGTERM
-trap stats_finalize EXIT
+trap "stats_finalize; rm -f $comma_test_run_flock" EXIT
 
 basedir=$( pwd )
 result=0
 
 stats_init
+
+# this function runs the actual test
+# arguments:
+#     test directory          - will cd and run the test inside
+#     stats file name         - will write start/stop time into this file
+#     test script executable  - the test to execute
+#     path to q-storage       - where the data are
+#     verbosity flag          - auxiliary, chatter more/less
+#     'grep failed' routine   - filters/not stderr output
+#     success_message         - print if all fine
+#     failure_message         - print if test fails
+function run_single_test()
+{
+    local dir=$1
+    local stats_progress=$2
+    local test_exec=$3
+    local path=$4
+    local verbose=$5
+    local grep_failed_=$6
+    local success_message=$7
+    local failure_message=$8
+
+    local basedir
+    basedir=$( pwd )
+
+    # create a unique file for local comma_progress output; will append to the main output at the end
+    local our_stats_progress="$stats_progress.$(mktemp -u XXXXXX)"
+
+    # create a unique file for redirecting all output; will append to the main output at the end
+    local our_stdout_log=$( mktemp --tmpdir=$( dirname "$stats_progress" ) )
+    exec 3>&1 4>&2 1>"$our_stdout_log" 2>&1
+
+    local result=0
+
+    cd "$dir"
+    if [ -f ./input ] ; then cat ./input ; fi \
+        | comma_progress_named "$our_stats_progress" "$dir" "$test_exec" "$path" "$verbose" 2> >( "$grep_failed_" >&2 ) \
+        | if [[ -f ./expected ]]; then comma-test-match ./expected 2>&1 | fail_on_output; else cat > /dev/null; fi
+    if status_ok ; then message_ "$success_message" ; else result=1 ; error_ "$failure_message" ; fi
+    cd $basedir
+
+    # serialize all access to global resources: stats file, stdout/err
+    exec 8>"$comma_test_run_flock"
+    flock -x 8
+    cat "$our_stats_progress" >> "$stats_progress"
+    cat "$our_stdout_log" >&3
+    flock -u 8
+    exec 8>&-
+
+    rm -f "$our_stats_progress"
+    rm -f "$our_stdout_log"
+
+    return $result
+}
+export -f run_single_test
+
+# to run 
 
 # search for directories containing either "test", "input" or "expected";
 # if "test" is absent, use the "test" in the closest parent directory
@@ -192,15 +259,16 @@ if (( $test_scripts_count > 0 )) ; then
         if [[ -z "$test_exec" ]]; then error_ "$name: error: no \"test\" script found in any parent directory of $dir" >&2 ; continue ; fi
         message_ "$name: test $count of $test_scripts_count: $dir: running..."
         ## Comment out for now: the exact usage to be discussed, it is confusing and can be taken as a sign of error
-        ##[ -f "$dir/readme" ] && dump_file_ "$dir/readme" 
-        basedir=$( pwd )
-        cd $dir
-        if [ -f ./input ] ; then cat ./input ; fi \
-            | comma_progress_named $stats_progress_csv "$dir" "$test_exec" $path $verbose 2> >( $grep_failed_ >&2 ) \
-            | if [[ -f ./expected ]]; then comma-test-match ./expected 2>&1 | fail_on_output; else cat > /dev/null; fi
-        if status_ok ; then message_ "$name: test $count of $test_scripts_count: $dir: succeeded" ; else result=1 ; (( ++failed_count )) ; error_ "$name: $dir: failed" ; fi
-        cd $basedir
-        if [[ "$result" != 0 && "$until_first_failure" == true ]] ; then break ; fi
+        ##[ -f "$dir/readme" ] && dump_file_ "$dir/readme"
+        run_single_test "$dir" "$stats_progress_csv" "$test_exec" "$path" "$verbose" "$grep_failed_" "$name: test $count of $test_scripts_count: $dir: succeeded" "$name: $dir: failed" &
+        single_test_pid=$!
+        wait $single_test_pid
+        single_test_result=$?
+        if [[ "$single_test_result" != 0 ]] ; then
+            result=$single_test_result
+            (( ++failed_count ))
+            if [[ "$until_first_failure" == true ]] ; then break ; fi
+        fi
     done
     if [[ "$result" == 0 ]] ; then message_ "$name: in subdirectories of $( pwd ): succeeded" ; else error_ "$name: $test_scripts_count test[s] in subdirectories of $( pwd ): $failed_count test[s] out of $test_scripts_count failed" ; fi
 fi
