Minor: improve description and error messages in the total_system_resources function.

diff --git a/util/resources-util b/util/resources-util
--- a/util/resources-util
+++ b/util/resources-util
@@ -66,22 +66,22 @@ function queue_is_empty()
 }
 
 # Output the most commonly used system resources: number of CPUs, total RAM,
-# size, total shared memory size.
+# size, total shared memory size. No arguments. Do not read stdin.
 function total_system_resources()
 {
-    local cpus memory_main memory_shared memory_limits fcn_name
-    fcn_name=${name:-"total_system_resources"}
+    local cpus memory_main memory_shared memory_limits
+    local name=${name:-"total_system_resources"}
     cpus=$( grep -c '^processor' /proc/cpuinfo )
-    (( $? == 0 || $cpus > 0 )) || { echo "$fcn_name: cannot grep '/proc/cpuinfo' for the number of processors" >&2; return 1; }
+    (( $? == 0 || $cpus > 0 )) || { echo "$name: cannot grep '/proc/cpuinfo' for the number of processors" >&2; return 1; }
     #
     memory_limits=$( ipcs -ml 2>/dev/null )
-    (( $? == 0 )) || { echo "$fcn_name: cannot determine memory limits by calling ipcs" >&2; exit 1; }
+    (( $? == 0 )) || { echo "$name: cannot determine memory limits by calling ipcs" >&2; exit 1; }
     memory_shared=$( echo "$memory_limits" | sed '/shared/!d;s/.* //g' )
-    (( $memory_shared > 0 )) || { echo "$fcn_name: cannot determine shared memory size" >&2; exit 1; }
+    (( $memory_shared > 0 )) || { echo "$name: cannot determine shared memory size" >&2; exit 1; }
     memory_shared=$(( $memory_shared * 1024 ))
     #
     memory_main=$( cat /proc/meminfo | sed -n --regexp-extended "s/^MemTotal: *(.*) .*$/\1/p" )
-    (( $memory_main > 0 )) || { echo "$fcn_name: cannot determine total memory size" >&2; exit 1; }
+    (( $memory_main > 0 )) || { echo "$name: cannot determine total memory size" >&2; exit 1; }
     memory_main=$(( $memory_main * 1024 ))
     #
     echo "resources/cpus=\"$cpus\""
