system/package: trying to make it work for ubuntu 18.04 with numpy 1.13...

diff --git a/system/package/comma-package-test b/system/package/comma-package-test
--- a/system/package/comma-package-test
+++ b/system/package/comma-package-test
@@ -20,7 +20,7 @@ type -p comma-application-util || die "failed: failed"
 echo "$0: testing bash utils: done"
 
 echo "$0: testing csv-eval..."
-output=$( csv-paste line-number | head | csv-eval --fields a "a+=1" || exit ) || die "failed: failed to run"
+output=$( seq 0 9 | csv-eval --fields a "a+=1" || exit ) || die "failed: failed to run"
 expected=$( seq 1 10 )
 [[ "$output" == "$expected" ]] || die "failed: unexpected output: $output"
 echo "$0: testing csv-eval: done"
