python: packaging...

diff --git a/system/package/comma-package-make b/system/package/comma-package-make
--- a/system/package/comma-package-make
+++ b/system/package/comma-package-make
@@ -29,8 +29,8 @@ esac
             -DCPACK_PACKAGE_VERSION_PATCH=$version_patch  || die "failed"
     echo "$0: running cpack in $( pwd )" >&2
     cpack || die "failed"
-    #cd ~/src/comma/python
-    #echo "$0: setting up python in $( pwd )" >&2
-    #python3 setup.py --command-packages=stdeb.command bdist_deb || die "failed"
+    cd ~/src/comma/python
+    echo "$0: setting up python in $( pwd )" >&2
+    python3 setup.py --command-packages=stdeb.command bdist_deb || die "failed"
     echo "$0: done" >&2
 )
