system/package: making python included in deb

diff --git a/system/package/comma-package-make b/system/package/comma-package-make
--- a/system/package/comma-package-make
+++ b/system/package/comma-package-make
@@ -14,7 +14,11 @@ ansible-playbook "$comma_dir/system/ansible/install.python3.yml" || die "failed"
 (
     cd ~/build/comma
     echo "$0: running cmake in $( pwd )" >&2
-    cmake . -DCPACK_GENERATOR=DEB -DCPACK_PACKAGE_VERSION_MAJOR=$version_major -DCPACK_PACKAGE_VERSION_MINOR=$version_minor -DCPACK_PACKAGE_VERSION_PATCH=$version_patch  || die "failed"
+    cmake . -DCPACK_GENERATOR=DEB \
+            -DADD_PYTHON_PACKAGES_TO_RPM=ON \
+            -DCPACK_PACKAGE_VERSION_MAJOR=$version_major \
+            -DCPACK_PACKAGE_VERSION_MINOR=$version_minor \
+            -DCPACK_PACKAGE_VERSION_PATCH=$version_patch  || die "failed"
     echo "$0: running cpack in $( pwd )" >&2
     cpack || die "failed"
     #cd ~/src/comma/python
diff --git a/system/package/comma-package-test b/system/package/comma-package-test
--- a/system/package/comma-package-test
+++ b/system/package/comma-package-test
@@ -6,6 +6,14 @@ package="$1"
 [[ -n "$package" ]] || { echo "usage: $0 <package>" >&2; exit 1; }
 apt install --yes "$package" || die "failed to install package '$package'"
 
-# todo
+echo "$0: testing basic csv utilities..."
+output=$( csv-paste line-number | head | csv-to-bin ui | csv-from-bin ui ) || die "failed: failed to run"
+expected=$( seq 0 9 )
+[[ "$output" == "$expected" ]] || die "failed: unexpected output: $output"
+echo "$0: testing basic csv utilities: done"
 
-csv-paste line-number | csv-to-bin ui | csv-from-bin ui | head >&2
+echo "$0: testing csv-eval..."
+output=$( csv-paste line-number | head | csv-eval --fields a "a+=1" || exit ) || die "failed: failed to run"
+expected=$( seq 1 10 )
+[[ "$output" == "$expected" ]] || die "failed: unexpected output: $output"
+echo "$0: testing csv-eval: done"
