comma-process-util: observed that ps is occasionally hanging (forever) when parsing processes being killed (Google search indicates that the problem is common enough). To make it worse, ps hangs heavily and only 'kill -9' gets rid of it. Wrap the call into timeout, with a mandatory 'kill -9' after 10 seconds of inactivity. Re-arranged the code a bit to accommodate this hack.

diff --git a/bash/process/comma-process-util b/bash/process/comma-process-util
--- a/bash/process/comma-process-util
+++ b/bash/process/comma-process-util
@@ -257,13 +257,8 @@ function comma_wait_for_process_group()
     local max_wait_time=$3
     [[ -n "$max_wait_time" ]] || max_wait_time="forever"
     local iter=0
-    local leftovers leftovers_count
+    local leftovers leftovers_count leftovers_rv
     while true ; do
-        leftovers=$( ps --no-headers -u $USER -o pgid,pid,comm | grep "^ *$process_group_id " | grep -v '<defunct>' )
-        leftovers_count=$( echo "$leftovers" | sed '/^$/d' | wc -l )
-        leftovers=$( echo -n "$leftovers" | tr '\n' ',' )
-        (( leftovers_count > 0 )) && { echo "$caller_name: waited ${iter}s for $process_group_id, still $leftovers_count processes left ('$leftovers')" >&2; sleep 1; } || { return 0; }
-        (( ++iter ))
         if [[ "$max_wait_time" != "forever" ]] ; then
             (( iter > max_wait_time )) && {
                 echo "$caller_name: exceeded ${max_wait_time}s timeout in waiting for $process_group_id" >&2
@@ -272,6 +267,14 @@ function comma_wait_for_process_group()
                 return 1
             }
         fi
+        # occasionally observed ps hanging here indefinitely
+        leftovers=$( timeout -k 10 -s TERM 10 bash -c "ps --no-headers -u $USER -o pgid,pid,comm | grep \"^ *$process_group_id \" | grep -v '<defunct>'" )
+        leftovers_rv=$?
+        (( leftovers_rv >= 126 )) && { echo "$caller_name: could not list processes in group $process_group_id (status '$leftovers_rv')" >&2; (( ++iter )); sleep 1; continue; }
+        leftovers_count=$( echo "$leftovers" | sed '/^$/d' | wc -l )
+        leftovers=$( echo -n "$leftovers" | tr '\n' ',' )
+        (( leftovers_count > 0 )) && { echo "$caller_name: waited ${iter}s for $process_group_id, still $leftovers_count processes left ('$leftovers')" >&2; sleep 1; } || { return 0; }
+        (( ++iter ))
     done
 }
 export -f comma_wait_for_process_group
