comma-process-util, comma-background-util, tests: s/comma_kill_signed/comma_process_kill s/comma_kill_signed_return_trap/comma_process_kill_trap_return_ s/COMMA_KILL_SIGNED_/COMMA_PROCESS_KILL_

diff --git a/bash/process/comma-background-util b/bash/process/comma-background-util
--- a/bash/process/comma-background-util
+++ b/bash/process/comma-background-util
@@ -36,14 +36,14 @@
 # @brief functions used to start background processes and verify their process ids
 #
 # @section comma_background_util_constants Constants
-# @li @link COMMA_KILL_SIGNED_ERROR @endlink
-# @li @link COMMA_KILL_SIGNED_NOT_FOUND @endlink
-# @li @link COMMA_KILL_SIGNED_REUSED @endlink
+# @li @link COMMA_PROCESS_KILL_ERROR @endlink
+# @li @link COMMA_PROCESS_KILL_NOT_FOUND @endlink
+# @li @link COMMA_PROCESS_KILL_REUSED @endlink
 #
 # @section comma_background_util_functions Functions
 # @li @link comma_process_signature @endlink
-# @li @link comma_kill_signed_return_trap @endlink
-# @li @link comma_kill_signed @endlink
+# @li @link comma_process_kill_trap_return_ @endlink
+# @li @link comma_process_kill @endlink
 # @li @link comma_process_launch @endlink
 # @li @link comma_process_validate @endlink
 # @li @link comma_process_launch_and_validate @endlink
@@ -75,33 +75,33 @@ function comma_process_signature()
 export -f comma_process_signature
 declare -r comma_process_signature
 
-## @page COMMA_KILL_SIGNED_ERROR COMMA_KILL_SIGNED_ERROR
-# @brief exit status of @link comma_kill_signed @endlink in case of internal errors
-export COMMA_KILL_SIGNED_ERROR=1
-declare -r COMMA_KILL_SIGNED_ERROR
+## @page COMMA_PROCESS_KILL_ERROR COMMA_PROCESS_KILL_ERROR
+# @brief exit status of @link comma_process_kill @endlink in case of internal errors
+export COMMA_PROCESS_KILL_ERROR=1
+declare -r COMMA_PROCESS_KILL_ERROR
 
-## @page COMMA_KILL_SIGNED_NOT_FOUND COMMA_KILL_SIGNED_NOT_FOUND
-# @brief exit status of @link comma_kill_signed @endlink if the process to be killed is not in the process tree (terminated already)
-export COMMA_KILL_SIGNED_NOT_FOUND=3
-declare -r COMMA_KILL_SIGNED_NOT_FOUND
+## @page COMMA_PROCESS_KILL_NOT_FOUND COMMA_PROCESS_KILL_NOT_FOUND
+# @brief exit status of @link comma_process_kill @endlink if the process to be killed is not in the process tree (terminated already)
+export COMMA_PROCESS_KILL_NOT_FOUND=3
+declare -r COMMA_PROCESS_KILL_NOT_FOUND
 
-## @page COMMA_KILL_SIGNED_REUSED COMMA_KILL_SIGNED_REUSED
-# @brief exit status of @link comma_kill_signed @endlink if the process to be killed shows a different signature (PID reused)
-export COMMA_KILL_SIGNED_REUSED=4
-declare -r COMMA_KILL_SIGNED_REUSED
+## @page COMMA_PROCESS_KILL_REUSED COMMA_PROCESS_KILL_REUSED
+# @brief exit status of @link comma_process_kill @endlink if the process to be killed shows a different signature (PID reused)
+export COMMA_PROCESS_KILL_REUSED=4
+declare -r COMMA_PROCESS_KILL_REUSED
 
-## @page comma_kill_signed_return_trap comma_kill_signed_return_trap
-# @brief auxiliary, the return trap for @link comma_kill_signed @endlink
-function comma_kill_signed_return_trap()
+## @page comma_process_kill_trap_return_ comma_process_kill_trap_return_
+# @brief auxiliary, the return trap for @link comma_process_kill @endlink
+function comma_process_kill_trap_return_()
 {
     (( verbose == 1 )) && builtin echo "$FUNCNAME: send CONT to $pid" >&2
     builtin kill -s CONT $pid
     trap - RETURN
 }
-export -f comma_kill_signed_return_trap
-declare -r comma_kill_signed_return_trap
+export -f comma_process_kill_trap_return_
+declare -r comma_process_kill_trap_return_
 
-## @page comma_kill_signed comma_kill_signed
+## @page comma_process_kill comma_process_kill
 # @description check if the given process id has the given descriptor
 # (see @link comma_process_signature @endlink) and kill it with TERM if so.
 # Does nothing if the process is not found.
@@ -109,12 +109,12 @@ declare -r comma_kill_signed_return_trap
 # @param signal-to-use optional; if equal to '--signal=SIGNAL', use SIGNAL as kill argument; otherwise taken as first argument
 # @param pid process id to query; start with '-' to kill the process group
 # @param signature unique process descriptor to compare
-# @return 0 on success (process found, signature matched, process killed), @link COMMA_KILL_SIGNED_NOT_FOUND @endlink
-# on internal errors (cannot determine current process signature), @link COMMA_KILL_SIGNED_NOT_FOUND @endlink
-# if the process is not found (already terminated), and @link COMMA_KILL_SIGNED_REUSED @endlink on signature mismatch;
+# @return 0 on success (process found, signature matched, process killed), @link COMMA_PROCESS_KILL_NOT_FOUND @endlink
+# on internal errors (cannot determine current process signature), @link COMMA_PROCESS_KILL_NOT_FOUND @endlink
+# if the process is not found (already terminated), and @link COMMA_PROCESS_KILL_REUSED @endlink on signature mismatch;
 # the last two cases may or may not be errors, only the user knows if the process being
 # killed is expected to exist or can exit by itself before calling this function
-function comma_kill_signed()
+function comma_process_kill()
 {
     local verbose=0
     local signal_to_use="TERM"
@@ -131,18 +131,18 @@ function comma_kill_signed()
     local group=${pid:0:1}
     [[ "$group" == "-" ]] && pid=${pid:1} || group=""
     (( verbose == 1 )) && builtin echo "$FUNCNAME: send signal '$signal_to_use' to ${group}${pid}" >&2
-    trap 'comma_kill_signed_return_trap' RETURN
+    trap 'comma_process_kill_trap_return_' RETURN
     builtin kill -s STOP $pid
-    (( $? == 0 )) || { builtin echo "$FUNCNAME: process id '$pid' not found; do not kill, assume terminated by itself" >&2; return $COMMA_KILL_SIGNED_NOT_FOUND; }
+    (( $? == 0 )) || { builtin echo "$FUNCNAME: process id '$pid' not found; do not kill, assume terminated by itself" >&2; return $COMMA_PROCESS_KILL_NOT_FOUND; }
     local current
     current=$( comma_process_signature $pid )
-    (( $? == 0 )) || { builtin echo "$FUNCNAME: cannot get signature of process id '$pid'" >&2; return $COMMA_KILL_SIGNED_ERROR; }
-    [[ "$current" == "$signature" ]] || { builtin echo "$FUNCNAME: process '$pid' has signature '$current' different from expected '$signature'; possibly re-used; refuse to kill" >&2; return $COMMA_KILL_SIGNED_REUSED; }
+    (( $? == 0 )) || { builtin echo "$FUNCNAME: cannot get signature of process id '$pid'" >&2; return $COMMA_PROCESS_KILL_ERROR; }
+    [[ "$current" == "$signature" ]] || { builtin echo "$FUNCNAME: process '$pid' has signature '$current' different from expected '$signature'; possibly re-used; refuse to kill" >&2; return $COMMA_PROCESS_KILL_REUSED; }
     (( verbose == 1 )) && builtin echo "$FUNCNAME: verification passed, do 'kill -s $signal_to_use ${group}${pid}'" >&2
     builtin kill -s $signal_to_use ${group}${pid}
 }
-export -f comma_kill_signed
-declare -r comma_kill_signed
+export -f comma_process_kill
+declare -r comma_process_kill
 
 ## @page comma_process_launch comma_process_launch
 # @description a wrapper to start background processes; immediately after launch writes
diff --git a/bash/process/comma-process-util b/bash/process/comma-process-util
--- a/bash/process/comma-process-util
+++ b/bash/process/comma-process-util
@@ -62,9 +62,9 @@ function terminate_comma_execute_and_wait()
         for command_to_execute_index in ${!commands_to_execute_pgid[@]} ; do
             if [[ -n "${commands_to_execute_pgid[$command_to_execute_index]}" ]] ; then
                 [[ "$comma_execute_and_wait_verbose" == "true" ]] && echo "$cew_funcname: killing ${commands_to_execute_pgid[$command_to_execute_index]} by $termination_signal" >&2
-                comma_kill_signed $comma_background_verbose --signal=$termination_signal ${killsign}${commands_to_execute_pgid[$command_to_execute_index]} ${commands_to_execute_signature[$command_to_execute_index]}
+                comma_process_kill $comma_background_verbose --signal=$termination_signal ${killsign}${commands_to_execute_pgid[$command_to_execute_index]} ${commands_to_execute_signature[$command_to_execute_index]}
                 # ignore the not found and reused exit status: the original process is gone, multiple background processes can terminate at different times
-                (( $? == COMMA_KILL_SIGNED_ERROR )) && echo "$cew_funcname: error in comma_kill_signed $comma_background_verbose --signal=$termination_signal ${killsign}${commands_to_execute_pgid[$command_to_execute_index]} ${commands_to_execute_signature[$command_to_execute_index]}" >&2
+                (( $? == COMMA_PROCESS_KILL_ERROR )) && echo "$cew_funcname: error in comma_process_kill $comma_background_verbose --signal=$termination_signal ${killsign}${commands_to_execute_pgid[$command_to_execute_index]} ${commands_to_execute_signature[$command_to_execute_index]}" >&2
                 [[ "$killsign" == "-" ]] && {
                     [[ "$comma_execute_and_wait_verbose" == "true" ]] && echo "$cew_funcname: waiting for group ${commands_to_execute_pgid[$command_to_execute_index]}" >&2
                     comma_wait_for_process_group "$cew_funcname" "${commands_to_execute_pgid[$command_to_execute_index]}" 25
