comma-background-util: plug the signature calculations into background launcher: the child calculates its own signature, the parent reads it (for now into a variable with a standard name, to be made user-defined later).

diff --git a/bash/process/comma-background-util b/bash/process/comma-background-util
--- a/bash/process/comma-background-util
+++ b/bash/process/comma-background-util
@@ -119,9 +119,11 @@ function comma_background_launcher()
     [[ "$fifo" == "--verbose" ]] && { verbose=1 ; fifo=$1 ; shift ; }
     (( verbose == 0 )) || builtin echo "$FUNCNAME: run in PID '$self'" >&2
     [[ -p "$fifo" ]] || { builtin echo "$FUNCNAME: '$fifo' is not a FIFO" >&2; return 1; }
-    builtin echo "$self" > "$fifo"
+    local signature
+    signature=$( comma_get_process_signature $self ) || { builtin echo "$FUNCNAME: cannot get process signature for '$self'" >&2; return 1; }
+    builtin echo "$self $signature" > "$fifo"
     (( verbose == 0 )) || builtin echo "$FUNCNAME: in PID '$self': exec '${@}'" >&2
-    unset verbose self fifo
+    unset verbose self fifo signature
     exec "${@}"
 }
 export -f comma_background_launcher
@@ -139,14 +141,15 @@ function comma_verify_background_pid()
     local fifo=$1
     [[ "$fifo" == "--verbose" ]] && { verbose=1 ; shift; fifo=$1 ; }
     local expected=$2
-    local pid status
+    # TODO provide an option to control the name of the signature variable, e.g., --signature-name=variable_name; exec the assignment
+    local pid comma_background_signature status
     local timeout=10
     # http://stackoverflow.com/questions/6448632/read-not-timing-out-when-reading-from-pipe-in-bash
     # Your shell is blocking on the open() call before invoking the read builtin.
     #
     # On Linux, you can open the FIFO for both read and write at the same time to prevent blocking on open; this is non-portable, but may do what you want.
     (( verbose == 0 )) || builtin echo "$FUNCNAME: attempt to read pid from '$fifo' for $timeout seconds ..." >&2
-    read -t $timeout pid <> "$fifo"
+    read -t $timeout pid comma_background_signature <> "$fifo"
     status=$?
     (( status == 0 )) || {
         builtin echo "$FUNCNAME: could not read process id from '$fifo' in $timeout seconds or read error, status '$status'" >&2
