comma-background-util: the previous commit not enough, ps restores default (apparently) signal disposition and can be interrupted. Check the exit status of ps to see if it was killed, and re-run if so. Exit on error exits as before.

diff --git a/bash/process/comma-background-util b/bash/process/comma-background-util
--- a/bash/process/comma-background-util
+++ b/bash/process/comma-background-util
@@ -66,9 +66,13 @@ function comma_process_signature()
     local verbose=0
     local pid=$1
     [[ "$pid" == "--verbose" ]] && { verbose=1 ; shift ; pid=$1 ; }
-    local signature
-    signature=$( ps --no-headers -o lstart $pid )
-    (( $? == 0 )) || { builtin echo "$FUNCNAME: process with id '$pid' not found" >&2; return 1; }
+    local signature psexit
+    while true ; do
+        signature=$( ps --no-headers -o lstart "$pid" )
+        psexit=$?
+        (( $psexit > 128 )) || { builtin echo "$FUNCNAME: ps killed by a signal, try again" >&2; continue; }
+        (( $psexit == 0 )) || { builtin echo "$FUNCNAME: process with id '$pid' not found" >&2; return 1; }
+    done
     signature=$( date --date="$signature" +%Y%m%dT%H%M%S ) || { builtin echo "$FUNCNAME: cannot convert '$signature' to timestamp" >&2; return 1; }
     (( verbose == 0 )) || builtin echo "$FUNCNAME: process '$pid' signed as '$signature'" >&2
     echo "$signature"
