comma-process-util: refactor comma_process_kill to work in a subprocess and use an EXIT trap instead of a less reliable RETURN trap.

diff --git a/bash/process/comma-process-util b/bash/process/comma-process-util
--- a/bash/process/comma-process-util
+++ b/bash/process/comma-process-util
@@ -44,7 +44,8 @@
 #
 # @section comma_process_util_functions Functions
 # @li @link comma_process_signature @endlink
-# @li @link comma_process_kill_trap_return_ @endlink
+# @li @link comma_process_kill_trap_exit_ @endlink
+# @li @link comma_process_kill_helper_ @endlink
 # @li @link comma_process_kill @endlink
 # @li @link comma_process_exec @endlink
 # @li @link comma_process_validate @endlink
@@ -120,20 +121,17 @@ declare -r COMMA_PROCESS_KILL_NOT_FOUND
 export COMMA_PROCESS_KILL_REUSED=4
 declare -r COMMA_PROCESS_KILL_REUSED
 
-## @page comma_process_kill_trap_return_ comma_process_kill_trap_return_
-# @brief auxiliary, the return trap for @link comma_process_kill @endlink
-function comma_process_kill_trap_return_()
+## @page comma_process_kill_trap_exit_ comma_process_kill_trap_exit_
+# @brief auxiliary, the exit trap for @link comma_process_helper_ @endlink
+function comma_process_kill_trap_exit_()
 {
-    # restore EXIT trap from before comma_process_kill() was called
-    [[ -n "$comma_process_kill_exit_trap_command" ]] && trap "$comma_process_kill_exit_trap_command" EXIT
     (( verbose == 1 )) && builtin echo "$FUNCNAME: send CONT to $pid" >&2
     builtin kill -s CONT $pid
-    trap - RETURN
 }
-export -f comma_process_kill_trap_return_
-declare -r comma_process_kill_trap_return_
+export -f comma_process_kill_trap_exit_
+declare -r comma_process_kill_trap_exit_
 
-## @page comma_process_kill comma_process_kill
+## @page comma_process_kill_helper_ comma_process_kill_helper_
 # @description check if the given process id has the given descriptor
 # (see @link comma_process_signature @endlink) and kill it with TERM if so.
 # Does nothing if the process is not found.
@@ -146,10 +144,11 @@ declare -r comma_process_kill_trap_return_
 # if the process is not found (already terminated), and @link COMMA_PROCESS_KILL_REUSED @endlink on signature mismatch;
 # the last two cases may or may not be errors, only the user knows if the process being
 # killed is expected to exist or can exit by itself before calling this function
-function comma_process_kill()
+function comma_process_kill_helper_()
 {
-    local verbose=0
-    local signal_to_use="TERM"
+    # to be invoked in a subshell, do not bother with local variables
+    verbose=0
+    signal_to_use="TERM"
     while true; do
         case $1 in
             --signal=*) signal_to_use=${1#*=};;
@@ -158,26 +157,32 @@ function comma_process_kill()
         esac
         shift
     done
-    local pid=$1
+    pid=$1
     # do not change to [[ ]] here
     if [ "$pid" -eq "$pid" ] ; then :; else builtin echo "$FUNCNAME: pid '$pid' is not an integer" >&2; return 1; fi
-    local signature=$2
-    local group=${pid:0:1}
+    signature=$2
+    group=${pid:0:1}
     [[ "$group" == "-" ]] && pid=${pid:1} || group=""
     (( verbose == 1 )) && builtin echo "$FUNCNAME: send signal '$signal_to_use' to ${group}${pid}" >&2
-    # store current exit traps (global so it can be used in comma_process_kill_trap_return_)
-    comma_process_kill_exit_trap_command=$( comma_get_trap "EXIT" )
-    # keep previous EXIT trap command (we can't just say "trap 'comma_process_kill_trap_return_' RETURN EXIT", since that won't call the previous trap command)
-    [[ -n "$comma_process_kill_exit_trap_command" ]] && trap "comma_process_kill_trap_return_; $comma_process_kill_exit_trap_command" EXIT
-    trap 'comma_process_kill_trap_return_' RETURN
+    trap 'comma_process_kill_trap_exit_' EXIT
     builtin kill -s STOP $pid
-    (( $? == 0 )) || { builtin echo "$FUNCNAME: process id '$pid' not found; do not kill, assume terminated by itself" >&2; return $COMMA_PROCESS_KILL_NOT_FOUND; }
-    local current
+    (( $? == 0 )) || { builtin echo "$FUNCNAME: process id '$pid' not found; do not kill, assume terminated by itself" >&2; exit $COMMA_PROCESS_KILL_NOT_FOUND; }
     current=$( comma_process_signature $pid )
-    (( $? == 0 )) || { builtin echo "$FUNCNAME: cannot get signature of process id '$pid'" >&2; return $COMMA_PROCESS_KILL_ERROR; }
-    [[ "$current" == "$signature" ]] || { builtin echo "$FUNCNAME: process '$pid' has signature '$current' different from expected '$signature'; possibly re-used; refuse to kill" >&2; return $COMMA_PROCESS_KILL_REUSED; }
+    (( $? == 0 )) || { builtin echo "$FUNCNAME: cannot get signature of process id '$pid'" >&2; exit $COMMA_PROCESS_KILL_ERROR; }
+    [[ "$current" == "$signature" ]] || { builtin echo "$FUNCNAME: process '$pid' has signature '$current' different from expected '$signature'; possibly re-used; refuse to kill" >&2; exit $COMMA_PROCESS_KILL_REUSED; }
     (( verbose == 1 )) && builtin echo "$FUNCNAME: verification passed, do 'kill -s $signal_to_use ${group}${pid}'" >&2
     builtin kill -s $signal_to_use ${group}${pid}
+}
+export -f comma_process_kill_helper_
+declare -r comma_process_kill_helper_
+
+## @page comma_process_kill comma_process_kill
+# @description invokes @link comma_process_kill_helper_ @endlink in a subshell
+# to setup a custom EXIT trap
+function comma_process_kill()
+{
+    # subshell to use a different EXIT trap
+    bash -c "comma_process_kill_helper_ $*"
 }
 export -f comma_process_kill
 declare -r comma_process_kill
