comma-process-util: when comma_execute_and_wait is invoked in debugging (verbose) mode, pass '--verbose' to comma-background-util functions as well.

diff --git a/bash/process/comma-process-util b/bash/process/comma-process-util
--- a/bash/process/comma-process-util
+++ b/bash/process/comma-process-util
@@ -64,9 +64,9 @@ function terminate_comma_execute_and_wait()
                 [[ "$comma_execute_and_wait_verbose" == "true" ]] && echo "$cew_funcname: killing ${commands_to_execute_pgid[$command_to_execute_index]} by $termination_signal" >&2
                 # kill -s $termination_signal -- ${killsign}${commands_to_execute_pgid[$command_to_execute_index]}
                 # TODO specify the signal
-                comma_kill_signed ${killsign}${commands_to_execute_pgid[$command_to_execute_index]} ${commands_to_execute_signature[$command_to_execute_index]}
+                comma_kill_signed $comma_background_verbose ${killsign}${commands_to_execute_pgid[$command_to_execute_index]} ${commands_to_execute_signature[$command_to_execute_index]}
                 # ignore the not found and reused exit status: the original process is gone, multiple background processes can terminate at different times
-                (( $? == COMMA_KILL_SIGNED_ERROR )) && echo "$cew_funcname: error in comma_kill_signed ${killsign}${commands_to_execute_pgid[$command_to_execute_index]} ${commands_to_execute_signature[$command_to_execute_index]}" >&2
+                (( $? == COMMA_KILL_SIGNED_ERROR )) && echo "$cew_funcname: error in comma_kill_signed $comma_background_verbose ${killsign}${commands_to_execute_pgid[$command_to_execute_index]} ${commands_to_execute_signature[$command_to_execute_index]}" >&2
                 [[ "$killsign" == "-" ]] && {
                     [[ "$comma_execute_and_wait_verbose" == "true" ]] && echo "$cew_funcname: waiting for group ${commands_to_execute_pgid[$command_to_execute_index]}" >&2
                     comma_wait_for_process_group "$cew_funcname" "${commands_to_execute_pgid[$command_to_execute_index]}" 25
@@ -177,6 +177,7 @@ function comma_execute_and_wait()
     local usepg="true"
     local statusall="true"
     local comma_execute_and_wait_verbose="false" # "true"
+    local comma_background_verbose=
     local pid_fifo=
     local rm_pid_fifo="false"
     local cew_verified_pids=0
@@ -199,6 +200,7 @@ function comma_execute_and_wait()
         echo "$cew_funcname: conflicting timeout and process options (called: comma_execute_and_wait $original_args)" >&2
         return 1
     fi
+    [[ "$comma_execute_and_wait_verbose" == "true" ]] && comma_background_verbose="--verbose"
 
     [[ -n "$pid_fifo" ]] && {
         [[ -p "$pid_fifo" ]] || { echo "$cew_funcname: fifo argument '$pid_fifo' is not a named pipe" >&2; return 1; }
@@ -245,15 +247,15 @@ function comma_execute_and_wait()
         # its own process group and under timeout
         if [[ "$usepg" == "true" ]] ; then
             if [[ "$shellfcn" == "true" ]] ; then
-                comma_background_and_verify_pid "$pid_fifo" timeout -k 10 -s TERM $execute_and_wait_timeout bash -c "$command_to_execute"
+                comma_background_and_verify_pid $comma_background_verbose "$pid_fifo" timeout -k 10 -s TERM $execute_and_wait_timeout bash -c "$command_to_execute"
             else
-                comma_background_and_verify_pid "$pid_fifo" timeout -k 10 -s TERM $execute_and_wait_timeout $command_to_execute
+                comma_background_and_verify_pid $comma_background_verbose "$pid_fifo" timeout -k 10 -s TERM $execute_and_wait_timeout $command_to_execute
             fi
         else
             if [[ "$shellfcn" == "true" ]] ; then
-                comma_background_and_verify_pid "$pid_fifo" bash -c "$command_to_execute"
+                comma_background_and_verify_pid $comma_background_verbose "$pid_fifo" bash -c "$command_to_execute"
             else
-                comma_background_and_verify_pid "$pid_fifo" $command_to_execute
+                comma_background_and_verify_pid $comma_background_verbose "$pid_fifo" $command_to_execute
             fi
         fi
         (( $? == 0 )) || {
@@ -261,7 +263,7 @@ function comma_execute_and_wait()
             kill -s TERM $BASHPID  # go into our signal handler
         }
         commands_to_execute_pgid+=( $! )
-        commands_to_execute_signature+=( $comma_background_signature )
+        commands_to_execute_signature+=( $comma_background_signature $comma_background_verbose )
     done
     cew_verified_pids=1
     # do not need it anymore
