system/package/debian/comma-package-make: fixing...

diff --git a/system/package/debian/comma-package-make b/system/package/debian/comma-package-make
--- a/system/package/debian/comma-package-make
+++ b/system/package/debian/comma-package-make
@@ -21,7 +21,7 @@ esac
 
 (
     cd ~/build/comma
-    echo "$0: running cmake in $( pwd )" >&2
+    echo "$0: running cmake in $( pwd )..." >&2
     cmake . -DCPACK_GENERATOR=DEB \
             -DBUILD_PYTHON_PACKAGES=OFF \
             -DADD_PYTHON_PACKAGES_TO_RPM=OFF \
@@ -37,9 +37,9 @@ esac
             -DCMAKE_PROJECT_VERSION_PATCH=$version_patch  \
             -Dcomma_INSTALL_LIB_DIR=lib/x86_64-linux-gnu \
             -Dcomma_BUILD_XML=OFF \
-            -Dcomma_build_io_rabbit_cat=OFF || die "failed"
-    echo "$0: running cpack in $( pwd )" >&2
-    cpack || die "failed"
+            -Dcomma_build_io_rabbit_cat=OFF || die "cmake failed"
+    echo "$0: running cpack in $( pwd )..." >&2
+    cpack || die "cpack failed"
     echo "$0: created package at $( realpath comma-$version_major.$version_minor.$version_patch-Linux.deb )" >&2
     # todo: optionally run full regression test
     echo "$0: done" >&2
