system/package/debian/comma-package-make: typo fixed

diff --git a/system/package/debian/comma-package-make b/system/package/debian/comma-package-make
--- a/system/package/debian/comma-package-make
+++ b/system/package/debian/comma-package-make
@@ -10,8 +10,8 @@ comma_dir="$5"
 [[ -n "$comma_dir" ]] || comma_dir=$( realpath ~/src/comma )
 [[ -n "$version_patch" ]] || { echo "usage: $0 <ubuntu version> <comma version major> <comma version minor> <comma version patch> [<comma dir>]" >&2; exit 1; }
 cd ~
-echo "$0: running ansible-playbook '$comma_dir/system/ansible/install.python3.yml' in $( pwd )..." >&2
-ansible-playbook "$comma_dir/system/ansible/install.python3.yml" || die "failed"
+echo "$0: running ansible-playbook '$comma_dir/system/ansible/install.yml' in $( pwd )..." >&2
+ansible-playbook "$comma_dir/system/ansible/install.yml" || die "failed"
 case $ubuntu_version in
     18.04) libproc_version="libprocps6 (>= 2:3.3.0)" ;;
     20.04) libproc_version="libprocps8 (>= 1)" ;;
