packaging: fixed lintian errors, todo: new error to fix after gpg-signing the package: misplaced-extra-member-in-deb

diff --git a/system/package/debian/comma-package-make b/system/package/debian/comma-package-make
--- a/system/package/debian/comma-package-make
+++ b/system/package/debian/comma-package-make
@@ -20,16 +20,17 @@ esac
 (
     cd ~/src/comma/python
     echo "$0: setting up python in $( pwd )" >&2
-    python3 setup.py --command-packages=stdeb.command bdist_deb || die "failed"
-    
-    
+    #python3 setup.py --command-packages=stdeb.command bdist_deb || die "failed"
+    echo "$0: running python3 setup.py ..." >&2
+    python3 setup.py --command-packages=stdeb.command sdist_dsc --copyright-file ../copyright || die "failed"
+    echo "$0: building package..." >&2
+    cd deb_dist/comma-$version_major.$version_minor.$version_patch || die "failed"
+    dpkg-buildpackage -rfakeroot -uc -us || die "failed"
     #https://shallowsky.com/blog/programming/packaging-launchpad-ppas.html
-    # todo: python3 setup.py --command-packages=stdeb.command sdist_dsc --copyright-file ../copyright
-    # todo: optionally gpg key
+    # todo? optionally gpg key
     # todo? add lintian check?
-    # todo? or do all above outside of this script?
-    
-    
+    # todo? or do all above outside of this script using:
+    #       debsigs --sign=origin -k 79BF9724F37751A39B08698DB3CB85AF5FB6E9F1 comma-1.0.0-Linux.deb
     cd ~/build/comma
     echo "$0: running cmake in $( pwd )" >&2
     cmake . -DCPACK_GENERATOR=DEB \
