name_value/test/eval: fixed in a quick and dirty way (was failing, since the test is too sensitive and expects the error messages from python to match; but depending on python version, the error messages may vary); todo: refactor the test completely to remove assumptions about the python error messages?

diff --git a/name_value/test/eval/test b/name_value/test/eval/test
--- a/name_value/test/eval/test
+++ b/name_value/test/eval/test
@@ -31,7 +31,7 @@ total_count=0
 python_version="$( python -c "from __future__ import print_function; import sys; print( sys.version_info.major )" )" # sigh...
 python_prefix="python${python_version}:"
 
-for input in $data_dir/input*; do
+for input in $data_dir/input_*; do # for input in $data_dir/input*; do
     (( ++total_count ))
     suffix=${input#*input_}
     if (( verbose )); then echo "$name: running test $suffix" >&2; fi
@@ -47,8 +47,18 @@ for input in $data_dir/input*; do
     if ! cmp --quiet $stdout $data_dir/stdout_$suffix; then
         echo "$name: test failed for input_$suffix (stdout is different):" >&2
         diff $stdout $data_dir/stdout_$suffix >&2
-    elif ! cmp --quiet <( echo "$actual_stderr" ) <( echo "$expected_stderr" ); then
-        diff <( echo "$actual_stderr" ) <( echo "$expected_stderr" ) >&2
+    elif [[ "$actual_stderr" != "$expected_stderr" ]]; then # quick and dirty; sigh...
+        # quick and dirty; sigh... error messages keep changing from one python version to the next
+        if (( python_version == 2 )) || [[ "$( cut -d: -f3 <<< "$actual_stderr" )" != "$( cut -d: -f3 <<< "$expected_stderr" )" ]]; then
+            echo "expected error message:" >&2
+            echo "$expected_stderr" | sed 's#^#    #' >&2
+            echo "actual error message:" >&2
+            echo "$actual_stderr" | sed 's#^#    #' >&2
+        else
+            (( ++pass_count ))
+            if (( verbose )); then echo "$name: test $suffix passed" >&2; fi
+            echo $(basename "$input" )"=\"pass\""
+        fi
     else
         (( ++pass_count ))
         if (( verbose )); then echo "$name: test $suffix passed" >&2; fi
