Bug-fix: was not properly checking exit status of name-value-convert and thus not propagating the error exit status on broken input json files.

diff --git a/name_value/applications/name-value-calc b/name_value/applications/name-value-calc
--- a/name_value/applications/name-value-calc
+++ b/name_value/applications/name-value-calc
@@ -270,6 +270,15 @@ else
 fi
 
 file_separator="@-@-@-@-@"
+function feed_input()
+{
+    local file
+    for file in "${input_files[@]}"; do
+        $convert_input < "$file"
+        (( $? == 0 )) || { echo "$name: cannot parse '$file'" >&2; return 1; }
+        echo "$file_separator"
+    done
+}
 
-( for file in "${input_files[@]}"; do $convert_input < "$file"; echo $file_separator; done ) | python_converter | $convert_output
+feed_input | python_converter | $convert_output
 if ! status_ok; then exit 1; else exit 0; fi
