name-value-calc: extend to allow operating on file descriptors in process substitution mode of bash, e.g., name-value-calc <( cat 1 ) <( echo "$a")

diff --git a/name_value/applications/name-value-calc b/name_value/applications/name-value-calc
--- a/name_value/applications/name-value-calc
+++ b/name_value/applications/name-value-calc
@@ -232,7 +232,7 @@ if [[ -z "$operation" ]]; then echo "$name: operation must be specified (e.g. --
 if binary_op "$operation" && [[ ${#input_files[@]} > 2 ]]; then echo "$name: only two input files permitted with $operation operation"; exit 1; fi
 
 for file in "${input_files[@]}"; do
-    if [[ ! -f "$file" ]]; then echo "$name: cannot open '$file'" >&2; exit 1; fi
+    if [[ ! -r "$file" ]]; then echo "$name: cannot open '$file'" >&2; exit 1; fi
 done
 
 convert_input="cat"
