comma-test-util - created two files with the same name and broke everything

diff --git a/util/test/test_run/black_white/test b/util/test/test_run/black_white/test
--- a/util/test/test_run/black_white/test
+++ b/util/test/test_run/black_white/test
@@ -2,30 +2,15 @@
 
 name=$( basename $0 )
 
-function handle()
-{
-    [[ -n "$workdir" ]] && rm -rf "$workdir"
-}
+source $( type -p comma-test-util ) || exit 1
 
-trap 'handle' EXIT
+mkdir -p 'output' || exit 1
+export output_dir="$( readlink -f 'output' )"
 
-output_dir="output"
-output_dir=$( readlink -f "$output_dir" )
-
-tarball="../data/sample.tar"
-[[ -f "$tarball" ]] || {
-    echo "$name: file '$tarball' not found" >&2
-    exit 1
-}
-tarball=$( readlink -f "$tarball" )
-
-workdir=$( mktemp --directory --tmpdir="$output_dir" )
-cd "$workdir"
-tar xf "$tarball" || exit 1
-cd sample || exit 1
-comma-test-run --raw --white-list=white.list --black-list=black.list $@ > "$output_dir/log" 2>"$output_dir/log2"
-(( $? == 0 )) || exit 1
+comma_test_run_tarball '../data/sample.tar'  --white-list=white.list --black-list=black.list
 
 elapsed="stats/elapsed.csv"
-[[ -r "$elapsed" ]] || exit 1
+[[ -r "$elapsed" ]] || { echo "Could not access '$elapsed'" >&2 ; exit 1 ; }
 cat "$elapsed" | sed 's@^\./@@'
+
+exit 0
