Moved the former test to app and provided a test in comma-test-run style, with the expected file to match.

diff --git a/stress/application/signals/pkilled/test b/stress/application/signals/pkilled/test
--- a/stress/application/signals/pkilled/test
+++ b/stress/application/signals/pkilled/test
@@ -2,107 +2,16 @@
 
 name=$( basename $0 )
 
-function clean_up()
-{
-    trap '' SIGTERM # ignore signals
-    echo "killed, clean up in $name ($BASHPID, subshell $BASH_SUBSHELL)..." >&2
-    rm -rf "$output"
-    pkill --signal TERM -P $BASHPID
-    wait
-    echo "do not touch for $bed_time s..." >&2
-    exit 1
-}
-export -f clean_up
+app="./app"
+[[ -x "$app" ]] || { echo "$name: application '$app' not found" >&2; exit 1; }
 
-function handler()
-{
-    trap '' SIGTERM # ignore signals
-    echo "killed, handler in $BASHPID, subshell $BASH_SUBSHELL" >&2
-    pkill --signal TERM -P $BASHPID
-    wait
-    exit 1
-}
-export -f handler
+outdir="output"
+rm -rf "$outdir" || exit 1
+mkdir -p "$outdir" || exit 1
 
-# handle signals (clean up and exit)
-trap 'clean_up' SIGTERM
-
-function grandchild()
-{
-    local rank=$1
-    local stage=$2
-    local delay=$3
-    trap 'handler' SIGTERM
-    ./nap $delay >&2 &
-    wait
-    echo "$stage grandchild of parent $rank exit normally" >&2
-}
-export -f grandchild
-
-function child()
-{
-    local rank=$1    # our worker number
-    local num=$2     # number of grandchildren to spawn
-    local pipe=$3    # wait for the command on this fifo
-    local delay=$4   # time for offspring to sleep
-    trap 'handler' SIGTERM
-    local ip cmd
-    echo "child of $rank started as PID $BASHPID" >&2
-    # first spawn
-    for ip in $( seq $num ) ; do
-        grandchild $rank "early" $delay &
-    done
-    echo "child $rank finished eary parenting" >&2
-    read cmd < $pipe
-    [[ "$cmd" == "true" ]] && {
-        # second spawn
-        echo "child $rank start late parenting" >&2
-        for ip in $( seq $num ) ; do
-            grandchild $rank "late" $delay &
-        done
-    }
-    wait
-    echo "child $rank exit normally" >&2
-    return 0
-}
-export -f child
-
-# Fine-tune these parameters
-num_children=8
-num_larvae=256
-bed_time=600
-spawn_trigger="true"
-do_kill="true"
-trigger_delay=10
-
-pipes=""
-output=$( mktemp -d )
-log="log"
-rm -f "$log"
-
-echo "Top-level script is running as PID $BASHPID" >> "$log"
-
-# create children
-for n in $( seq $num_children ) ; do
-    pipe="$output/pipe${n}"
-    pipes="$pipes $pipe"
-    mkfifo "$pipe" || exit 1
-    child $n $num_larvae $pipe $bed_time >> "$log" 2>&1 &
+for n in $( seq 10 ) ; do
+    log="$outdir/$n.log"
+    $app "$outdir" > "$log" 2>&1
+    (( $? == 0 )) && { echo "$name: application was supposed to fail, but did not, see '$log'" >&2; exit 1; }
+    grep -c exit "$log" | sed "s/^/count[$n]=/"
 done
-
-# let the grandchildren goto sleep
-sleep $trigger_delay
-
-# optionally trigger second spawning
-for pipe in $pipes ; do
-    echo "$spawn_trigger" > "$pipe"
-done
-
-[[ "$do_kill" == "true" ]] && {
-    echo "bring the house down" >> "$log"
-    kill -s TERM $BASHPID
-}
-
-wait
-rm -rf "$output"
-echo "normal exit" >&2
