comma-background-util, former pid-fifo-util: moved the prototypes to their appropriate locations, renamed the main *-util script and functions therein, updated all tests to use the new function names. All tests pass. Updated the installation rules.

diff --git a/bash/test/comma_background/basic/failure/test b/bash/test/comma_background/basic/failure/test
--- a/bash/test/comma_background/basic/failure/test
+++ b/bash/test/comma_background/basic/failure/test
@@ -2,8 +2,8 @@
 
 readonly scriptname=$( basename "$0" )
 
-util="../../../pid-fifo-util"
-source "$util" || { echo "$scriptname: cannot source '$util'" >&2; exit 1; }
+util="comma-background-util"
+source $( which "$util" ) || { echo "$scriptname: cannot source '$util'" >&2; exit 1; }
 
 main_pid=$BASHPID
 echo "$scriptname: running as PID $main_pid" >&2
@@ -28,10 +28,10 @@ for i in $( eval echo "{1..$child_count}" ) ; do
     builtin echo "$scriptname: attempt to start a background process..." >&2
     # break the logic
     echo $bad_boy > "$fifo" &
-    background_launcher "$fifo" sleep 1 & last_child=$!
+    comma_background_launcher "$fifo" sleep 1 & last_child=$!
     echo "child[$i]/pid=$last_child"
     builtin echo "$scriptname: launched background child '$last_child', now verify..." >&2
-    verify_background_process_id "$fifo" $last_child
+    comma_verify_background_pid "$fifo" $last_child
     echo "child[$i]/verification/status=$?"
     children+=( $last_child )
 done
diff --git a/bash/test/comma_background/groups/test b/bash/test/comma_background/groups/test
--- a/bash/test/comma_background/groups/test
+++ b/bash/test/comma_background/groups/test
@@ -2,8 +2,8 @@
 
 scriptname=$( dirname "$0" )
 
-util="../../pid-fifo-util"
-source "$util" || { echo "$scriptname: cannot source '$util'" >&2; exit 1; }
+util="comma-background-util"
+source $( which "$util" ) || { echo "$scriptname: cannot source '$util'" >&2; exit 1; }
 
 output_dir="output"
 mkdir -p "$output_dir" || { echo "$scriptname: cannot create directory '$output_dir'" >&2; exit 1; }
@@ -40,7 +40,7 @@ export main_pid=$BASHPID
 echo "main is PID $main_pid" >&2
 
 for i in 0 1 ; do
-    launch_background_and_verify "$fifo" timeout -k 10 -s TERM 20 bash -c run_as_group\ "$output_dir/log${i}"
+    comma_background_and_verify_pid "$fifo" timeout -k 10 -s TERM 20 bash -c run_as_group\ "$output_dir/log${i}"
     echo "child[$i]/verification/status='$?'"
     echo "child[$i]/pid='$!'"
 done
diff --git a/test/stress/util/background/basic/main b/test/stress/util/background/basic/main
--- a/test/stress/util/background/basic/main
+++ b/test/stress/util/background/basic/main
@@ -2,17 +2,17 @@
 
 readonly scriptname=$( basename "$0" )
 
-util="../../../pid-fifo-util"
-source "$util" || { echo "$scriptname: cannot source '$util'" >&2; exit 1; }
-
-main_pid=$BASHPID
-echo "$scriptname: running as PID $main_pid" >&2
+util="comma-background-util"
+source $( which "$util" ) || { echo "cannot source '$util'" >&2; exit 1; }
 
 function report_own_tree()
 {
-    echo "$scriptname: process tree of main:"
+    echo "process tree of main:"
     pstree -a -c -g -l -p $main_pid
 }
+
+export main_pid=$BASHPID
+echo "main is PID $main_pid" >&2
 
 fifo=$( mktemp --dry-run )
 trap "rm -f '$fifo'" EXIT
@@ -20,15 +20,11 @@ mkfifo "$fifo" || { echo "$scriptname: cannot create FIFO '$fifo'" >&2; exit 1; 
 echo "$scriptname: use fifo '$fifo'" >&2
 
 children=()
-child_count=3
-echo "child/count=$child_count"
-for i in $( eval echo "{1..$child_count}" ) ; do
+for n in {1..3} ; do
     builtin echo "$scriptname: attempt to start a background process..." >&2
-    background_launcher "$fifo" sleep 1 & last_child=$!
-    echo "child[$i]/pid=$last_child"
+    comma_background_launcher "$fifo" sleep 1 & last_child=$!
     builtin echo "$scriptname: launched background child '$last_child', now verify..." >&2
-    verify_background_process_id "$fifo" $last_child
-    echo "child[$i]/verification/status=$?"
+    comma_verify_background_pid "$fifo" $last_child || { pkill --signal TERM -P $main_pid; wait; exit 1; }
     children+=( $last_child )
 done
 
