comma-application-util: swiss init: unnamed options: bug fixed

diff --git a/bash/comma-application-util b/bash/comma-application-util
--- a/bash/comma-application-util
+++ b/bash/comma-application-util
@@ -1,34 +1,7 @@
 #!/bin/bash
 
-# This file is part of comma, a generic and flexible library
 # Copyright (c) 2011 The University of Sydney
 # Copyright (c) 2020 Vsevolod Vlaskine
-# All rights reserved.
-#
-# Redistribution and use in source and binary forms, with or without
-# modification, are permitted provided that the following conditions are met:
-# 1. Redistributions of source code must retain the above copyright
-#    notice, this list of conditions and the following disclaimer.
-# 2. Redistributions in binary form must reproduce the above copyright
-#    notice, this list of conditions and the following disclaimer in the
-#    documentation and/or other materials provided with the distribution.
-# 3. Neither the name of the University of Sydney nor the
-#    names of its contributors may be used to endorse or promote products
-#    derived from this software without specific prior written permission.
-#
-# NO EXPRESS OR IMPLIED LICENSES TO ANY PARTY'S PATENT RIGHTS ARE
-# GRANTED BY THIS LICENSE.  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT
-# HOLDERS AND CONTRIBUTORS \"AS IS\" AND ANY EXPRESS OR IMPLIED
-# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
-# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
-# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
-# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
-# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
-# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
-# BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
-# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
-# OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN
-# IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
 ## @page comma-application-util comma-application-util
 # this script is designed to be included in another script directly, for example:
@@ -292,7 +265,8 @@ function comma-application-swiss-init()
     function verbose() { (( ! options_verbose )) || echo "$comma_application_name: ${comma_application_swiss_operation}: $@" >&2; }
     function die() { say "$@"; exit 1; }
     [[ $( type -t ${comma_application_swiss_operation}-run ) == "function" ]] || die "expected operation, got '${comma_application_swiss_operation}'" # quick and dirty
-    local options; options=$( ( echo "$common_options"; comma-application-common-options ) | comma-options-to-name-value "$@" ) || die "invalid options"
+    local options_described=$( echo "$common_options"; comma-application-common-options )
+    local options; options=$( comma-options-to-name-value "$@" <<< "$options_described" ) || die "invalid options"
     eval "$( grep -v '^"' <<< "$options" | sed 's#^#options_#' | comma_path_value_mangle )"
     #(( !options_verbose )) || verbose_option="--verbose"
     #(( !options_input_fields )) || { eval "echo \$${operation//-/_}_input_fields"; exit 0; } # quick and dirty
@@ -300,10 +274,11 @@ function comma-application-swiss-init()
     #(( !options_output_fields )) || { eval "echo \$${operation//-/_}_output_fields"; exit 0; } # quick and dirty
     #(( !options_output_format )) || { eval "echo \$${operation//-/_}_output_format"; exit 0; } # quick and dirty
     if [[ $( type -t ${comma_application_swiss_operation}-options ) == "function" ]]; then
-        local operation_options; operation_options=$( ${comma_application_swiss_operation}-options | comma-options-to-name-value "$@" ) || die "invalid options"
+        local operation_options_described=$( ${comma_application_swiss_operation}-options )
+        local operation_options; operation_options=$( comma-options-to-name-value "$@" <<< "$operation_options_described" ) || die "invalid options"
         eval "$( grep -v '^"' <<< "$operation_options" | sed 's#^#options_#' | comma_path_value_mangle )"
     fi
-    mapfile -t options_unnamed < <( ( echo "$options"; echo "$operation_options" ) | grep '^"' | sed -e 's#^"##' -e 's#"$##' )
+    mapfile -t options_unnamed < <( ( echo "$options_described"; echo "$operation_options_described"; ) | comma-options-to-name-value "$@" | grep '^"' | sed -e 's#^"##' -e 's#"$##' )
 }
 
 export -f comma-application-swiss-init
