comma-application-util: swiss util: application name made global to fix application name in the stderr messages

diff --git a/bash/comma-application-util b/bash/comma-application-util
--- a/bash/comma-application-util
+++ b/bash/comma-application-util
@@ -44,7 +44,7 @@
 [[ -n "$comma_application_util_include_guard_" ]] && return 0
 readonly comma_application_util_include_guard_=1
 
-source $( type -p comma-name-value-util ) || { echo "$name: cannot source 'comma-name-value-util' from '$BASH_SOURCE'" >&2; exit 1; }
+source $( type -p comma-name-value-util ) || { echo "$comma_application_name: cannot source 'comma-name-value-util' from '$BASH_SOURCE'" >&2; exit 1; }
 
 ## @page comma_options_from_name_value comma_options_from_name_value
 # @section comma_options_from_name_value
@@ -120,7 +120,7 @@ export -f comma_pretty_description
 
 ## @page comma_options_names comma_options_names
 # @description converts a standard comma description to a list of names
-# 
+#
 # example
 #   description | comma_options_names
 function comma_options_names()
@@ -132,7 +132,7 @@ export -f comma_options_names
 ## @page comma_options_to_bash_completion comma_options_to_bash_completion
 # @description converts a standard comma description to input
 # for the comma bash completion function
-# 
+#
 # example
 #   description | comma_options_to_bash_completion
 function comma_options_to_bash_completion()
@@ -144,7 +144,7 @@ export -f comma_options_to_bash_completion
 ## @page comma_options_select comma_options_select
 # @description after a set of options have been retrieved as paths convert to
 # options format for a child script
-# 
+#
 # example
 #   comma-test-run $( comma-test-run --description | comma-options-to-name-value $@ | comma_name_value_to_options )
 function comma_name_value_to_options()
@@ -272,9 +272,9 @@ export -f comma-application-init
 
 function comma-application-swiss-init()
 {
-    local name=$( basename "$0" )
+    comma_application_name=$( basename "$0" )
     local common_options=$( cat )
-    [[ -n "$1" ]] || { echo "$name: please specify operation" >&2; exit 1; }
+    [[ -n "$1" ]] || { echo "$comma_application_name: please specify operation" >&2; exit 1; }
     comma_application_swiss_operation="$1" # todo? quick and dirty, allow --help anywhere on the command line?
     if comma_options_help $@; then
         if [[ "${comma_application_swiss_operation}" == "--help" || "${comma_application_swiss_operation}" == "-h" ]]; then
@@ -287,9 +287,9 @@ function comma-application-swiss-init()
         fi >&2
         exit 0
     fi
-    function say() { echo "$name: ${comma_application_swiss_operation}: $@" >&2; }
-    function saymore() { (( ! options_verbose )) || echo "$name: ${comma_application_swiss_operation}: $@" >&2; }
-    function verbose() { (( ! options_verbose )) || echo "$name: ${comma_application_swiss_operation}: $@" >&2; }
+    function say() { echo "$comma_application_name: ${comma_application_swiss_operation}: $@" >&2; }
+    function saymore() { (( ! options_verbose )) || echo "$comma_application_name: ${comma_application_swiss_operation}: $@" >&2; }
+    function verbose() { (( ! options_verbose )) || echo "$comma_application_name: ${comma_application_swiss_operation}: $@" >&2; }
     function die() { say "$@"; exit 1; }
     [[ $( type -t ${comma_application_swiss_operation}-run ) == "function" ]] || die "expected operation, got '${comma_application_swiss_operation}'" # quick and dirty
     local options; options=$( ( echo "$common_options"; comma-application-common-options ) | comma-options-to-name-value "$@" ) || die "invalid options"
